### ISSUE TITLE
项目名称带有'-'，会使得corova初始化错误

### ISSUE THREAD

**Issue by xiaohuoni** [alitajs/alita#12]
当项目中带有 '-' ，执行 init失败
```sh
$alita cordova --init
```
需要给出错误提示，在执行命令的时候先判断项目名称，判断带有'-'
直接给出错误提示，不执行 `cordova create`

在执行`alita g app` 的时候，判断项目名称带有 '-' 
需要给出提示，"项目名称带有'-'，会导致后续cordova等功能不可用，建议修改"

**Comment by imhele** [comment]
给个配置项吧，不从 package.json 里读 name
https://github.com/alitajs/alita/blob/5c4b298b8271dcd8e1d979e1dcdccc7bf6d3c82b/packages/umi-plugin-cordova/src/index.ts#L86-L89
