### ISSUE TITLE
tabs-layout怎么配合Umi3的plugin-layout使用

### ISSUE THREAD

**Issue by Nokecy** [alitajs/alita#128]

**Comment by xiaohuoni** [comment]
首先 tabs-layout 是一个临时方案，等 umi 的 keepalive 出来，会有更好的方案实现。
然后要结合 plugin-layout 使用，需要修改它的运行时。
直接配置是不支持的，我 clone了他的代码。发布了一个私有包。你可以看看。
就改了4个地方，把 TabsLayout 传到了 layout 里面，对现有功能无破坏。
你只要把 @umijs/plugin-layout 改成 @alitajs/plugin-layout，
然后在 config 里面使用 plugins:['@alitajs/plugin-layout']

相关PR： https://github.com/umijs/plugins/pull/125

> @umijs/ 开头的插件会被自动引用，所以不需要在配置文件中写明。
