### ISSUE TITLE
动态路由无法匹配上

### ISSUE THREAD

**Issue by zengyuhang** [alitajs/alita#140]
https://umijs.org/zh-CN/docs/convention-routing#动态路由

试过在config中配置 
 keepalive: [
    '/goods/search/:type',
    '/goods/search/2',
    '/goods/search/',
  ],
均无法命中动态的约定式路由
goods/search/[type].tsx
页面访问路径 http://localhost:8000/#/goods/search/2
调试可以看到被包裹到了rumtime-keep-alive-layout-no中

**Comment by xiaohuoni** [comment]
可以写正则表达式 [\.\]
