### ISSUE TITLE
A request for shrinking the size of alita

### ISSUE THREAD

**Issue by DaleyThom** [alitajs/alita#149]
Hi, @xiaohuoni

According to npm’s installation rule, it parses the package.json based on the libraries’s declaration order, to construct the **node_modules** tree. For the libraries that have not been installed in the project, **node_modules** tree can share them by putting them at the top level of the tree. For the libraries that have been installed, it checks whether their specified version constraints are compatible with the installed ones. If yes, npm ignores them, otherwise, npm will put such duplicated libraries in the subfolders (npm’s sandboxes).

We installed and analyzed the alita, and found that it is large in size. alita’s **node_modules** tree has installed 2134 libraries. 1249 out of 2134 libraries are shared at the top level of the tree, while 885 libraries are the duplicated in the sandboxes. We further checked the duplicated libraries, and listed the them as follows (format: library name, version number, the number of installations on the **node_modules** tree). For example, “**source-map, 0.6.1, 85**” denotes that library ***source-map 0.6.1*** has been installed **85** times in this project.

<details>
  <summary>Clicking for details (duplicated libraries)—</summary>
    <br/> source-map, 0.6.1, 85
    <br/> chalk, 2.4.2, 77
    <br/> supports-color, 6.1.0, 76
    <br/> supports-color, 5.5.0, 75
    <br/> postcss, 7.0.32, 75
    <br/> rc-util, 5.0.4, 22
    <br/> postcss-value-parser, 3.3.1, 17
    <br/> isarray, 1.0.0, 16
    <br/> readable-stream, 2.3.7, 14
    <br/> string_decoder, 1.1.1, 14
    <br/> isobject, 3.0.1, 14
    <br/> mkdirp, 0.5.5, 12
    <br/> extend-shallow, 2.0.1, 11
    <br/> rc-animate, 3.1.0, 11
    <br/> ms, 2.1.2, 10
    <br/> kind-of, 6.0.3, 8
    <br/> rc-trigger, 4.3.0, 8
    <br/> rc-align, 4.0.0, 8
    <br/> bn.js, 4.11.9, 7
    <br/> debug, 4.1.1, 7
    <br/> ansi-regex, 2.1.1, 5
    <br/> warning, 4.0.3, 5
    <br/> schema-utils, 1.0.0, 5
    <br/> define-property, 0.2.5, 5
    <br/> is-accessor-descriptor, 1.0.0, 4
    <br/> is-data-descriptor, 1.0.0, 4
    <br/> is-descriptor, 1.0.2, 4
    <br/> strip-ansi, 6.0.0, 4
    <br/> path-to-regexp, 1.8.0, 4
    <br/> cssesc, 2.0.0, 4
    <br/> postcss-selector-parser, 5.0.0, 4
    <br/> loader-utils, 2.0.0, 4
    <br/> is-number, 3.0.0, 4
    <br/> kind-of, 3.2.2, 4
    <br/> ansi-regex, 5.0.0, 4
    <br/> define-property, 1.0.0, 3
    <br/> color-convert, 2.0.1, 3
    <br/> color-name, 1.1.4, 3
    <br/> path-key, 3.1.1, 3
    <br/> get-stream, 5.1.0, 3
    <br/> has-flag, 4.0.0, 3
    <br/> safe-buffer, 5.2.1, 3
    <br/> supports-color, 7.1.0, 3
    <br/> react-router, 5.1.2, 3
    <br/> mini-create-react-context, 0.3.2, 3
    <br/> is-fullwidth-code-point, 3.0.0, 3
    <br/> string-width, 4.2.0, 3
    <br/> react-router-dom, 5.1.2, 3
    <br/> babel-plugin-dynamic-import-node, 2.3.3, 3
    <br/> regenerator-runtime, 0.13.5, 3
    <br/> fs-extra, 7.0.1, 3
    <br/> camelcase, 5.3.1, 3
    <br/> ansi-styles, 2.2.1, 3
    <br/> range-parser, 1.2.1, 3
    <br/> chalk, 1.1.3, 3
    <br/> debug, 3.2.6, 3
    <br/> braces, 2.3.2, 3
    <br/> fill-range, 4.0.0, 3
    <br/> strip-ansi, 3.0.1, 3
    <br/> supports-color, 2.0.0, 3
    <br/> micromatch, 3.1.10, 3
    <br/> to-regex-range, 2.1.1, 3
    <br/> pify, 3.0.0, 3
    <br/> ajv, 6.12.2, 3
    <br/> fast-deep-equal, 3.1.3, 3
    <br/> ansi-styles, 4.2.1, 3
    <br/> postcss-selector-parser, 3.1.2, 3
    <br/> which, 2.0.2, 2
    <br/> glob-parent, 3.1.0, 2
    <br/> is-glob, 3.1.0, 2
    <br/> bytes, 3.1.0, 2
    <br/> qs, 6.7.0, 2
    <br/> resolve-from, 3.0.0, 2
    <br/> @babel/traverse, 7.10.0, 2
    <br/> find-up, 2.1.0, 2
    <br/> locate-path, 2.0.0, 2
    <br/> is-extendable, 1.0.1, 2
    <br/> punycode, 1.4.1, 2
    <br/> p-limit, 1.3.0, 2
    <br/> p-locate, 2.0.0, 2
    <br/> p-try, 1.0.0, 2
    <br/> is-stream, 2.0.0, 2
    <br/> readable-stream, 1.1.14, 2
    <br/> string_decoder, 0.10.31, 2
    <br/> npm-run-path, 4.0.1, 2
    <br/> set-value, 2.0.1, 2
    <br/> get-stream, 4.1.0, 2
    <br/> cross-spawn, 5.1.0, 2
    <br/> path-to-regexp, 2.4.0, 2
    <br/> inherits, 2.0.3, 2
    <br/> shebang-regex, 3.0.0, 2
    <br/> shebang-command, 2.0.0, 2
</details>

So many duplicated libraries could cause potential problems, such as: slower installs, exploding bundle sizes, and so on.

Based on npm’s installation rules, we comprehensively analyzed the compatibilities of all the transitive dependencies’ version ranges and the topological structure of your **node_modules** tree. We suggested alita add the following duplicated libraries with their compatible versions into the  package.json file (as shown in the attachment), which help to refactor the project’s **node_modules** tree. 

<details>
  <summary>Clicking for details—</summary>
 	<br/> "isarray": "1.0.0",
    <br/> "readable-stream": "2.3.6",
    <br/> "kind-of": "3.2.0",
    <br/> "ms": "2.1.1",
    <br/> "isobject": "3.0.1",
    <br/> "source-map": "0.6.1",
    <br/> "mkdirp": "0.5.3",
    <br/> "debug": "4.1.1",
    <br/> "extend-shallow": "2.0.1",
    <br/> "@babel/types": "7.10.2",
    <br/> "is-number": "3.0.0",
    <br/> "braces": "2.3.2",
    <br/> "pify": "3.0.0",
    <br/> "semver": "6.3.0",
    <br/> "supports-color": "6.1.0",
    <br/> "postcss": "7.0.27",
    <br/> "glob-parent": "3.1.0",
    <br/> "micromatch": "3.1.10",
    <br/> "find-up": "2.1.0",
    <br/> "path-key": "3.1.0",
    <br/> "ajv": "6.12.0",
    <br/> "strip-ansi": "5.2.0",
    <br/> "ansi-regex": "2.1.1",
    <br/> "path-type": "3.0.0",
    <br/> "emojis-list": "3.0.0",
    <br/> "chalk": "2.4.2",
    <br/> "camelcase": "5.3.1",
    <br/> "regenerator-runtime": "0.13.5",
    <br/> "@babel/parser": "7.9.4",
    <br/> "array-union": "1.0.2",
    <br/> "rc-util": "5.0.4",
    <br/> "postcss-value-parser": "3.3.1"
</details>

After cleaning the local installation environment and re-installing alita based on the revised package.json file, we found that the **node_modules** tree totally installs **1674** libraries, including the **1249** ones at the top level, **425** ones in the sandboxes. As such, the revised package.json file reduces **460** duplicated libraries for alita. In this manner, alita’s size is shrunk from **500MB** to **357MB**, reducing **7745files** (from **58189** to **50444**) and **1511** folders (from **7534** to **6023**) in total. Note that, all the added directed dependencies in package.json file are deduced based on the original **node_modules** tree, which will not miss any required dependencies.

Before refactoring dependency tree——
![1](https://user-images.githubusercontent.com/66732483/84572340-dfa01c80-adcb-11ea-8dbc-4daa288d5ab2.png)
After refactoring dependency tree——
![2](https://user-images.githubusercontent.com/66732483/84572356-ef1f6580-adcb-11ea-84cc-58bf1374db91.png)

[package.json.txt](https://github.com/alitajs/alita/files/4774872/package.json.txt)
[package-lock.json.txt](https://github.com/alitajs/alita/files/4774871/package-lock.json.txt)

Would you like to adopt this suggestion to shrink the project’s size?

Thank you for your attention.
Best regards.

**Comment by xiaohuoni** [comment]
@DaleyThom 👍！Thank you for your suggestion. I tried to use your plan, but it didn't seem to work.
## before
```
449,125,600 字节（磁盘上的652.7 MB），共75,067个项目
```
## after
```
453,594,476 字节（磁盘上的658 MB），共75,492个项目
```
## before
```
✔ Webpack
  Compiled successfully in 14.43s

 DONE  Compiled successfully in 14434ms                                                                                 11:26:19 AM

 File              Size                        Gzipped

 dist/umi.js       833.2 KB                    294.3 KB
 dist/umi.css      62.3 KB                     9.6 KB

  Images and other types of assets omitted.

✨  Done in 18.27s.
```
## after
```
alita build

✔ Webpack
  Compiled successfully in 15.43s

 DONE  Compiled successfully in 15429ms                                                                                 11:23:10 AM

 File              Size                        Gzipped

 dist/umi.js       833.2 KB                    294.3 KB
 dist/umi.css      62.3 KB                     9.6 KB

  Images and other types of assets omitted.

✨  Done in 19.22s.
```
Please guide me.
I've released a beta version, you can try it. 
```
alita@2.5.3-beta.0
```
