### ISSUE TITLE
执行-v的时候，也会跑其他插件

### ISSUE THREAD

**Issue by xiaohuoni** [alitajs/alita#15]
需要做判断过滤
比如执行 `alita -v` 也会运行cordova热更新服务器

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/2419

**Comment by xiaohuoni** [comment]
umi 在api.onStart中调用其他api会提示
![image](https://user-images.githubusercontent.com/11746742/58604125-d8dc5f80-82c5-11e9-98d9-c714daadabfb.png)

**Comment by imhele** [comment]
是的
