### ISSUE TITLE
[WIP] 编译方案优化

### ISSUE THREAD

**Issue by xiaohuoni** [alitajs/alita#152]
现在编译之后，在生产环境中，用不到 vendors.js

https://github.com/alitajs/alita/blob/2c78bef3a82502451f5f194976e3a591bbccca8f/packages/micro/src/index.ts#L109-L112

但是在编译的时候，还是一样生成了。

https://github.com/alitajs/alita/blob/2c78bef3a82502451f5f194976e3a591bbccca8f/packages/micro/src/index.ts#L90-L95

只是在编译成功之后，又用脚本删除了

https://github.com/alitajs/alita/blob/2c78bef3a82502451f5f194976e3a591bbccca8f/packages/micro/src/index.ts#L136-L140

不知道能不能直接不生成 vendors.js 文件。但是不影响其他文件的生成情况。

**Comment by xiaohuoni** [comment]
@programmer-yang

**Comment by programmer-yang** [comment]
虽然私下已经聊了一下方案，但还是写一下，方便记录。

我目前的想法就是在splitChunks.cacheGroups的规则过程中，记录一下`vendors`下的清单，然后通过一个组件，把这个清单暴露出去，让别人安装这个组件后编译的时候就会把这个清单里的库动态添加到`externals`里，来实现编译的时候不打包这些库。

然后就是在webview里动态注入这个`vendors.js`，当然，这里也可以写成一个动态逻辑，比如在app启动的时候去对比一下是否有新的`vendors.js`供下载，这样就不用频繁的更新app的办法。

**Comment by xiaohuoni** [comment]
> 然后就是在webview里动态注入这个vendors.js，当然，这里也可以写成一个动态逻辑，比如在app启动的时候去对比一下是否有新的vendors.js供下载，这样就不用频繁的更新app的办法。

这部分的管理，会依赖于容器来做。

**Comment by xiaohuoni** [comment]
和生成骨架屏冲突，骨架屏需要完整的产物，才能运行。 https://github.com/alitajs/alita/issues/153 
调整方案，发布之前执行 alita micro 手动修改产物。
