### ISSUE TITLE
[Feature Request] 生成静态骨架屏

### ISSUE THREAD

**Issue by xiaohuoni** [alitajs/alita#153]
完整方案见 https://github.com/alitajs/alita/issues/150
![image](https://user-images.githubusercontent.com/11746742/88384459-0431e000-cddf-11ea-94e0-3c5a9f7e7e01.png)

期望的效果是，用户打开网页的时候，就能看到骨架屏，但是这时候，react相关环境可能还没有启动。
```
<body><div id="root"><这里自动写骨架></div></body>
```
这样用户刚打开网页就以为项目启动了，体验极好。事实上还是一样的启动时间。

**Comment by CJY0208** [comment]
https://github.com/CJY0208/auto-skeleton-plugin

# AutoSkeletonPlugin

基于 [jsdom](https://github.com/jsdom/jsdom) 的、自动生成骨架的 Webpack 插件，工作方式参考 [prerender-spa-plugin](https://github.com/chrisvfritz/prerender-spa-plugin)

## 工作方式

1. 等待 webpack 完成打包

2. 启动一个本地静态服务器，按配置的 routes，用 jsdom 启动无头浏览器访问打包结果

3. jsdom 中页面完成渲染后，执行 [generateSkeleton](https://github.com/CJY0208/auto-skeleton-plugin/blob/master/src/generateSkeleton.js) 骨架生成方法，将内容转换为骨架

4. 截取当前页面的 innerHTML 作为骨架预渲染结果，输出成 html 文件

5. 根据配置的 staticDir 将 html 文件存进去，over

**Comment by CJY0208** [comment]
目前方案初步可用，有以下待优化项

1. [ ] 去除无效 css 样式，可参考 [uncss](https://github.com/uncss/uncss) 
2. [ ] 尽可能完善并拓展 [generateSkeleton](https://github.com/CJY0208/auto-skeleton-plugin/blob/master/src/generateSkeleton.js) 方法过程

**Comment by xiaohuoni** [comment]
https://github.com/alitajs/alita/pull/156
