### ISSUE TITLE
多标签tabs-layout插件切换标签后链接参数丢失

### ISSUE THREAD

**Issue by ivin97** [alitajs/alita#157]
## What happens?   
多标签能否支持带有参数的链接？   

场景：   
页面中有两标签TabA、TabB   
标签TabA对应href为： http://localhost:8000/detail?id=2&type=4   
当点击标签TabB，然后再切回TabA，则上面参数?id=2&type=4丢失了

**Comment by xiaohuoni** [comment]
是参数没有更新，还是参数没有传递？看你取数据的地方是否正确，因为 tabs 里，页面没有销毁，所以，要自己判断进入页面的时机
