### ISSUE TITLE
标签页tabs-layout的keek-alive失效

### ISSUE THREAD

**Issue by zlh1234** [alitajs/alita#158]
## Context
keek-alive未生效。
同时希望能够提供一个方法用于关闭某一个标签页。
- **Alita Version**: 2.5.7
- **Node Version**:10.15.3

**Comment by xiaohuoni** [comment]
是都不生效还是什么情况下不生效？是单独使用还是结合什么插件使用？

**Comment by zlh1234** [comment]
目前项目中只有列表页有keep-alive效果，表单页、详情页都没有。

自己通过修改.umi文件夹中的getPageView方法测试通过。
![image](https://user-images.githubusercontent.com/34914070/90105979-59776680-dd79-11ea-8396-c4cc2740b211.png)

**Comment by xiaohuoni** [comment]
那应该是大小写问题。还有可能是动态路由匹配的问题。
