### ISSUE TITLE
umi在安装 @alitajs/hd插件后，ant mobile组件内的字体变模糊

### ISSUE THREAD

**Issue by QUCT** [alitajs/alita#162]
umi.js中引入@alitajs/hd插件做高清适配，ant mobile组件内的字体变小并且模糊。

config.js配置如下：
plugins: ['@alitajs/hd'],
  hd: {
    // same as config.theme, default set @hd: 2px
    "theme": {},
    "px2rem": {
      "rootValue": 100,
      "unitPrecision": 5,
      "propWhiteList": [],
      "propBlackList": [],
      "exclude": false,
      "selectorBlackList": [],
      "ignoreIdentifier": false,
      "replace": true,
      "mediaQuery": false,
      "minPixelValue": 3
    }
  }

**Comment by QUCT** [comment]
该如何解决呢

**Comment by xiaohuoni** [comment]
你试试，只配置 `hd:{}` 就好。

**Comment by xiaohuoni** [comment]
然后变模糊是什么意思，给个截图。再给个重现demo。不明白你说的问题。

**Comment by xiaohuoni** [comment]
@QUCT cc
