### ISSUE TITLE
umi3使用@alitajs/hd启动报错

### ISSUE THREAD

**Issue by a3538333** [alitajs/alita#169]
我参照umi的issues对hd的解决方案，新构建了umi3的项目，然后yarn add @alitajs/hd --save了这个插件，按照实例在umirc.js里面配置了
`  plugins: ['@alitajs/hd'],
   hd:{}
`,
启动的时候报错

node_modules/@alitajs/hd/lib/index.js: Cannot read property 'getFile' of undefined (47, 29)

请问该怎么处理啊

**Comment by xiaohuoni** [comment]
有重现demo吗？尝试了一下，无法重现。
