### ISSUE TITLE
动态路由dropByCacheKey报错

### ISSUE THREAD

**Issue by whirly77cai** [alitajs/alita#186]
使用动态路由，类似 /books/:id时
alivePathName为[/books/1234]
KeepAliveViewMap只有key  /books/:id
DropByCacheKey执行到keepAliveViewMap[pathname].recreateTimes += 1;时会出现错误

**Comment by whirly77cai** [comment]
> 用的是哪个插件？

@alitajs/keep-alive

**Comment by xiaohuoni** [comment]
/:id/ 应该处理的了？你用的是哪个版本？有复现的demo看一下嘛？

**Comment by whirly77cai** [comment]
> /:id/ 应该处理的了？你用的是哪个版本？有复现的demo看一下嘛？

2.8.2，简单写了个demo，但放不上去sandbox。麻烦你下到本地看看
https://github.com/whirly77cai/umi-kp-demo

**Comment by xiaohuoni** [comment]
@whirly77cai 感谢指出问题。
