### ISSUE TITLE
手机横屏字体显示不正确

### ISSUE THREAD

**Issue by zjyfantasy** [alitajs/alita#196]
![image](https://user-images.githubusercontent.com/22555643/126098422-224c69d4-a1f4-4f51-8b22-fd538f201b93.png)
使用alita创建的项目，手机竖屏时显示正常，但是横屏的时候font-size计算好像有问题，导致字体变大
![image](https://user-images.githubusercontent.com/22555643/126098562-b8e9e582-c896-4d87-9f59-50ad85275382.png)
请问该怎么设置才能使横竖屏字体保持一致

**Comment by xiaohuoni** [comment]
为什么应用支持横屏（大笑😂）

**Comment by zjyfantasy** [comment]
> 为什么应用支持横屏（大笑😂）
做的事游戏应用，需要横屏显示，请问大神有什么解决方案吗

**Comment by xiaohuoni** [comment]
`hd:false` 然后用自己的适配方案吧。

**Comment by zjyfantasy** [comment]
> `hd:false` 然后用自己的适配方案吧。

配置`hd:false`之后，px不转换rem了，然后我这样配置了px2rem插件postcss-plugin-px2rem
`
extraPostCSSPlugins: [
    px2rem({
      rootValue: 100
    }),
  ],
`
我的设计稿是基于iphone6的，这样配置导致转换出来的元素看起来缩小了，设置rootValue: 50又有点大，我想问下rootValue该怎么计算

**Comment by xiaohuoni** [comment]
你如果用 rem 的话，和 hd 方案一样的。就么必要自己再写了。
问题是你横屏应用是不是应该按横屏设计？把宽当作 750.然后标注值都会减小。

**Comment by xiaohuoni** [comment]
可以加我微信，讨论下 yu_xiaohu
