### ISSUE TITLE
单独安装antd-moblie无法正常引入组件

### ISSUE THREAD

**Issue by callmeYe** [alitajs/alita#208]
These dependencies were not found:

* antd-mobile/es/button in ./src/pages/Login/index.tsx
* antd-mobile/es/button/style in ./src/pages/Login/index.tsx
* antd-mobile/es/input in ./src/pages/Login/index.tsx
* antd-mobile/es/input/style in ./src/pages/Login/index.tsx

To install them, you can run: npm install --save antd-mobile/es/button antd-mobile/es/button/style antd-mobile/es/input antd-mobile/es/input/style

**Comment by hapyboy** [comment]
什么时候支持antd-mobile@5?

**Comment by xiaohuoni** [comment]
antd-mobile@5 发正式版的时候，就支持。
现在也可以尝鲜。装 `@alitajs/plugin-antd-mobile`

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-mobile/issues/3972

**Comment by zzz6519003** [comment]
普遍都改配置解决啊   antd: { mobile: false },

**Comment by xiaohuoni** [comment]
等 alita@3 内置了 antd-mobile@5
