### ISSUE TITLE
alita 命令无法执行

### ISSUE THREAD

**Issue by zuojianjian** [alitajs/alita#210]
alita : 无法将“alita”项识别为 cmdlet、函数、脚本文件或可运行程序的名称
但是在执行yarn start命令时，实际执行的也是alita dev命令啊

起因使用 alita g pages hero 添加一个页面
![image](https://user-images.githubusercontent.com/20851340/141040391-22c15122-262f-4baa-a701-33a2a78eb477.png)
![image](https://user-images.githubusercontent.com/20851340/141040450-686a8639-981c-4dd9-9427-aea5c2b7fdb7.png)

**Comment by xiaohuoni** [comment]
你的node环境有问题。自己百度一下重新设置一下就好，
