### ISSUE TITLE
[Feature Request] 动态的底部 tabs

### ISSUE THREAD

**Issue by xiaohuoni** [alitajs/alita#211]
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by hang1017** [comment]
需求：
初始化的时候tab 是a,b,c 三个页面，然后进入到d页面后调用接口后，可能要修改tab 为 a,b,e 三个tab

建议：
alita 生成临时文件，能够支持修改底部 tab 的列表数据。

demo 及复现步骤:
[tabDemo.zip](https://github.com/alitajs/alita/files/7526385/tabDemo.zip)
打开项目后首页有详细的描述

**Comment by hang1017** [comment]
https://github.com/alitajs/alita/pull/212

**Comment by hang1017** [comment]
https://github.com/alitajs/alita/pull/212

完成该需求，并测试原功能：setPageNavBar、setTabBarList 的稳定性。

需求demo 和测试原功能 demo 如下，打开首页后即可根据按钮点击设置

[tabDemo.zip](https://github.com/alitajs/alita/files/7533387/tabDemo.zip)
：

**Comment by xiaohuoni** [comment]
https://github.com/alitajs/alita/pull/216
