### ISSUE TITLE
windows,run cmd: alita cordova --android ; error: run command failed, command cordova does not exists.

### ISSUE THREAD

**Issue by lijianxing123** [alitajs/alita#214]
Env: windows
run cmd: alita cordova --android 
Error: run command failed, command cordova does not exists.

**Comment by lijianxing123** [comment]
@zengyuhang

**Comment by lijianxing123** [comment]
![Dingtalk_20211116111516](https://user-images.githubusercontent.com/21306431/141889544-c1c03f0f-337b-4eb7-8358-93d9dcbc23f6.jpg)

**Comment by xiaohuoni** [comment]
yarn global add cordova
