### ISSUE TITLE
tabBar 和navBar 

### ISSUE THREAD

**Issue by lovesL** [alitajs/alita#218]
## Background
![image](https://user-images.githubusercontent.com/27960630/142837762-0b8743a6-dd5d-4c50-9239-7d3cecd440b4.png)
1.既然Mobile 都提供了 那直接抛个api出来  直接引入他的组件就好了嘛。
2.navBar里面的图标都支持ReactNode  为啥tabBar里面就不支持ReactNode了
3.底部导航栏当没设置icon，icon应该不显示文字自动居中，还有字体希望能支持更改字体大小
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by hang1017** [comment]
alita 当前使用的是 antd-mobileV2 版本。
等amtd5 发布正式版本，alita 内部会慢慢替换。

**Comment by xiaohuoni** [comment]
他要的这个功能，mobile@2 就能实现，评估一下有没有必要提供 @hang1017

**Comment by hang1017** [comment]
@xiaohuoni 
底部导航栏当没设置icon，文字自动居中 ---- 可以实现。
tabBar 文字大小设置 ---- 无法实现。
@lovesL 如果有需要的话，可以完成上述内容。

**Comment by xiaohuoni** [comment]
tabBar 文字大小设置 ---- 无法实现。我感觉这个很好实现？？？

**Comment by lovesL** [comment]
> @xiaohuoni 底部导航栏当没设置icon，文字自动居中 ---- 可以实现。 tabBar 文字大小设置 ---- 无法实现。 @lovesL 如果有需要的话，可以完成上述内容。
能实现就实现吧 不能弄的 等以后升级在弄 吧
