### ISSUE TITLE
针对umi 3.4.8的集成，无法进行添加

### ISSUE THREAD

**Issue by yangjiaqiao** [alitajs/alita#219]
![image](https://user-images.githubusercontent.com/51978469/142966880-0a266a2a-1ac3-44ab-b5e8-5ca98e616b68.png)

## 最小可复现仓库

> 请使用 `yarn create alita` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Alita 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by xiaohuoni** [comment]
什么东西？
