### ISSUE TITLE
alita build 报错

### ISSUE THREAD

**Issue by lovesL** [alitajs/alita#297]
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/27960630/163357163-2414b484-fde7-432a-aa76-0fd62b63b705.png">

以下是依赖
"dependencies": {
    "@alitajs/main-path": "^2.8.15",
    "@alitajs/utils": "^2.8.32",
    "@antv/f2": "^4.0.12",
    "@antv/f2-react": "^4.0.12",
    "@umijs/plugin-model": "2.6.2",
    "ahooks": "^2.10.12",
    "alita": "^2.8.32",
    "antd": "^4.19.3",
    "antd-mobile": "^5.9.2",
    "antd-mobile-icons": "^0.2.2",
    "cordova": "^11.0.0",
    "jsencrypt": "^3.2.1",
    "minio": "7.0.20",
    "ol": "^6.13.0",
    "react": "^17.0.2",
    "react-mobile-picker": "^0.1.13",
    "react-picker": "^1.2.17",
    "react-scripts": "^5.0.0",
    "sass-loader": "^12.6.0",
    "umi": "^3.5.20",
    "uview-ui": "^2.0.29"
  },

"devDependencies": {
    "@types/express": "^4.17.2",
    "@umijs/fabric": "2.0.0",
    "chalk": "^3.0.0",
    "cordova-android": "^10.1.1",
    "cordova-plugin-whitelist": "^1.3.5",
    "cross-env": "^6.0.3",
    "eslint": "6.8.0",
    "eslint-plugin-eslint-comments": "^3.1.2",
    "express": "^4.17.1",
    "lint-staged": "^9.5.0",
    "node-sass": "^7.0.1",
    "prettier": "^2.0.2",
    "stylelint": "^12.0.1",
    "yorkie": "^2.0.0"
  },

<img width="726" alt="image" src="https://user-images.githubusercontent.com/27960630/163357074-71e56820-1569-4cfd-a3be-22a73221682b.png">
node: v16.13.2

**Comment by lovesL** [comment]
还需要啥 我在补

**Comment by xiaohuoni** [comment]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/11746742/163505007-0aeb8fd2-4116-4343-b302-21a159534058.png">
已在微信群答疑
