### ISSUE TITLE
能否去掉navBar 默认的后退按钮

### ISSUE THREAD

**Issue by lovesL** [alitajs/alita#298]
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/27960630/163362735-8ac01255-3e2a-4a2a-bbc4-2e2ff08eb765.png">
我的页面布局是只有navBar  没有tabBar  

怎么才能隐藏

![image](https://user-images.githubusercontent.com/27960630/163362961-0ffb9394-9c20-4200-b33e-347187c523d1.png)

**Comment by xiaohuoni** [comment]
配置 icon 为空， onLeftClick 为空就可以  onLeftClick: () => {},
