### ISSUE TITLE
keep alive正则没有匹配上.

### ISSUE THREAD

**Issue by JTenacity** [alitajs/alita#305]
keepalive: [/\/lsm\/(.*)/]规则为这样配置的。但是页面访问的是/lsm/list没进入缓存

**Comment by hang1017** [comment]
@JTenacity 修改成 ['/lsm/list']

**Comment by JTenacity** [comment]
我要用正则，因为路径有很多 @hang1017

**Comment by hang1017** [comment]
@JTenacity 我试试做个兼容

**Comment by hang1017** [comment]
@JTenacity 提了一个 pr 看看作者收不收。

**Comment by xiaohuoni** [comment]
@JTenacity 正则写错了，`//lsm/(.*)/.test('/lsm/list')` undefined 
你试试 `/lsm/`

**Comment by JTenacity** [comment]
@xiaohuoni 我提的时候写错了，配置的你发的那个并没有生效

**Comment by xiaohuoni** [comment]
@JTenacity 看 demo 里的 https://github.com/alitajs/next-alita-app/blob/master/config/config.ts#L15
