### ISSUE TITLE
动态路由 未生效

### ISSUE THREAD

**Issue by wybiubiu1012** [alitajs/alita#310]
pages 中使用动态路由配置
![image](https://user-images.githubusercontent.com/20685608/168463539-744119b5-1bfc-4d1c-8731-d5b62e18591b.png)
访问时 报No routes matched location警告
在umi route 中发现未注册动态路由
<img width="960" alt="image" src="https://user-images.githubusercontent.com/20685608/168463589-1787ac91-fa57-4d29-8b5a-85f20bfb3840.png">

**Comment by xiaohuoni** [comment]
已知问题，在 umi@4 内统一修复

**Comment by xiaohuoni** [comment]
使用 `$index` 替换 `[index]`
