### ISSUE TITLE
按官方教程走到第三步就报错，修改一些，运行还是报错，问题太多

### ISSUE THREAD

**Issue by ghostrin** [alitajs/alita#338]
node 版本  v16.15.0
mac系统
初始安装：
npx browserslist@latest --update-db
Latest version:     1.0.30001354
Installed version:  1.0.30001354
caniuse-lite is up to date

第一步：yarn create alita react-template --pc
第二步：yarn install
第三步：yarn start 开始报错：

Invalid config keys: locale, accessLayout
Error: Invalid config keys: locale, accessLayout

修改：config/config.ts 如下：
import { defineConfig } from 'alita';

export default defineConfig({
  appType: 'pc',
  // locale: {
  //   baseSeparator:'-'
  // },
  // accessLayout: {
  //   iconNames: ['smile']
  // },
});

提示需要安装：To install it, you can run: npm install --save use-merge-value
安装后，可以跑起来。
访问  http://localhost:8000/#/，报错：

×
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `BasicLayout`.

对应的代码：
export default connect(({ global }: { global: GlobalModelState }) => ({
  global,
  notices: global.notices,
}))(BasicLayout);

BasicLayout 报错 ???

试过几次，都是如上，没法用！

**Comment by xiaohuoni** [comment]
create alita 的版本被我指到 alita@3 了，你可以 `yarn create alita@2.8.37 react-template --pc`

或者根据 alita@3 的文档进行 https://next.alitajs.com/zh-CN/docs/guides/boilerplate

**Comment by ghostrin** [comment]
1、删除全局的alita
2、重新全局安装alita@2.8.37 
3、执行yarn create alita react-template --pc  出现的问题跟之前一样
4、执行 pnpx create-alita@3.0.0-rc.7 可以安装成功，跑起来报错：
error - ./src/models/global.ts:24:26-35
export 'queryMenu' (imported as 'queryMenu') was not found in '@/services/api' (possible exports: query)

请问：你的那个版本支持umi4 + react18 + react router v6 + 多页tabs？
alita@3.0.0-rc.7，有umi4，但是用的是 react17，我想在umi4中实现react router v6 + 多页tabs？请大佬给点建议！多谢

（也许不该这里问，我看大佬也是umi成员之一，膜拜！）
