### ISSUE TITLE
tabsLayout 目前不支持动态路由

### ISSUE THREAD

**Issue by chj-damon** [alitajs/alita#345]
现在tabsLayout是以键值对的方式进行配置的，键是path，值是tabs上的文字。
如： '/home' : '首页'

但如果采用的是动态路由的话，目前把动态路由作为字符串的话会导致匹配失败。
如： 'users/:userId': '用户'

所以需要对这种情况进行支持

**Comment by xiaohuoni** [comment]
https://github.com/alitajs/alita/pull/354
