### ISSUE TITLE
菜单名称是动态获取的,tab无法找到正确名称

### ISSUE THREAD

**Issue by JoeCdy** [alitajs/alita#374]
![image](https://user-images.githubusercontent.com/52903128/176632747-7f8936e0-6740-491c-a008-e19f83e3492c.png)
![image](https://user-images.githubusercontent.com/52903128/176633095-d5ae3adb-3b2c-46a2-9e05-493158846e37.png)
![image](https://user-images.githubusercontent.com/52903128/176632843-20d1be3e-3e3e-4eac-aeeb-e69f497f7875.png)
可以动态传入菜单对象以获取正确的名称吗

**Comment by xiaohuoni** [comment]
试试运行时配置

```ts
export const tabsLayout = {
  local: {
    '/': '首页',
    '/users': '用户',
    '/foo': '其他',
  },
};
```

**Comment by xiaohuoni** [comment]
https://github.com/alitajs/alita/issues/436

**Comment by hejinguo** [comment]
> 试试运行时配置
> 
> ```ts
> export const tabsLayout = {
>   local: {
>     '/': '首页',
>     '/users': '用户',
>     '/foo': '其他',
>   },
> };
> ```

请问 tabsLayout 配置是加到哪里？
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/19966301/194832797-e1151e27-4f0e-4ce7-b1dd-7da22aee253d.png">

<img width="420" alt="image" src="https://user-images.githubusercontent.com/19966301/194832859-b8b41ce8-2444-4ef1-b3f9-bd6697a58dcf.png">

**Comment by xiaohuoni** [comment]
不是同一个插件，@alitajs/tabs-layout 插件是 umi3 系列的东西，这里回复的是 umi4 系列插件的用法
