### ISSUE TITLE
关于tabsLayout后期会新增一些附加功能不？

### ISSUE THREAD

**Issue by xu-Aurora** [alitajs/alita#387]
1. 点击浏览器刷新，缓存当前所有的tab
2. 右键附加功能，包括：刷新、关闭其他、关闭所有。。。。
3. tab栏始终保持有home页路由，home页路由不能关闭删除

**Comment by xiaohuoni** [comment]
关于1 应该不会支持，刷新浏览器，还要缓存就要做持久化存储，现在没有看到不较好的方案

关于2 可以考虑做，但是在浏览器中的右键操作，个人不是很建议

关于3 可以考虑加不允许关闭的页面

感兴趣你可以来实现，其实很简单，就是修改 antd 的tabs 组件，你现在就可以通过自定义layout实现。

**Comment by iceshu** [comment]
我有个问题 就是路由带query的时候。
1、切换tab的时候当切换到带quey的路由query会丢失，因为你记录的时候是pathname没有吧search带上
2、我自己修改远嘛带上query之后点击tab跳转路由没问题了，但是因为页面里要获取query的参数 用的方法是useSearchParams这个钩子，因为是做了页面的缓存，当前页面只是呗隐藏了其实dom还是在页面上，所以当你切换tab的时候 应该隐藏的页面还是会执行render的逻辑 ，比如 A页面带有query 切到了B的tab，此时A的方法里还是会走查找query 然后执行下面的逻辑
@xu-Aurora xu 我就是直接改源码 离开页面的时候吧所有的tab的key 都缓存起来，下次进来的时候先拿缓存的key去渲染tab。

**Comment by xiaohuoni** [comment]
@iceshu 我暂时没时间看这个，如果你有思路，欢迎贡献。

**Comment by chj-damon** [comment]
@xu-Aurora  https://github.com/alitajs/alita/pull/441 解第二个需求

**Comment by xiaohuoni** [comment]
> tab栏始终保持有home页路由，home页路由不能关闭删除
这个真的有实际需求嘛？
