### ISSUE TITLE
使用CLI初始化项目后无法正常启动

### ISSUE THREAD

**Issue by chenzheio** [alitajs/alita#399]
通过 ` yarn create alita project` 命令初始化项目后
直接启动项目报错

 - Unhandled Rejection (Error): register failed, invalid key mobileLayout from plugin 
 - Unhandled Rejection (TypeError): null is not an object (evaluating '(0,_core_plugin__WEBPACK_IMPORTED_MODULE_7__.getPluginManager)().applyPlugins')

依赖版本
``` 
    "@alita/flow": "*",
    "alita": "^3.0.5",
    "antd-mobile": "^5.15.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
```

**Comment by xiaohuoni** [comment]
奇怪，怎么 yarn 老是出错，你先试试 pnpx create-alita
