### ISSUE TITLE
tabsLayout在自定义layout中能否控制rootContainer节点的值

### ISSUE THREAD

**Issue by panghaoyuan** [alitajs/alita#407]
## 问题
在使用自定义layout时，tablayout直接挂载在root节点下。导致样式出现问题
![image](https://user-images.githubusercontent.com/28645409/187484987-f20917ec-bdd1-4d48-9db3-bb840a4dba48.png)

## antd pro自带的layout挂载节点
![image](https://user-images.githubusercontent.com/28645409/187484041-679cd599-933e-4bee-8887-9ec62c4e34a3.png)

## 自定义layout挂载节点
![image](https://user-images.githubusercontent.com/28645409/187484411-e09f7f95-e748-430c-bb81-14bb6c07995b.png)

**Comment by xiaohuoni** [comment]
是不是和插件使用顺序有关，能给一个复现吗？
我中后台没做

**Comment by xiaohuoni** [comment]
自定义 layout 用 useKeepOutlets 代替 useOutlets 即可，不要使用 presets 
参考 https://github.com/alitajs/alita/blob/05398892d5da0338c018fb8920650e48b3529e7d/examples/pro/src/app.tsx#L102
