### ISSUE TITLE
tabs 会出现标题undefined，且国际化失效

### ISSUE THREAD

**Issue by xiaohuoni** [alitajs/alita#420]
国际化没做

undefined 估计与嵌套有关

**Comment by zozopen** [comment]
尝试了一下，是需要写tabsLayout 才可以正常显示

**Comment by xiaohuoni** [comment]
https://github.com/alitajs/alita/issues/436

**Comment by hejinguo** [comment]
> 
请问 tabsLayout 写在哪里的？

**Comment by hejinguo** [comment]
> 尝试了一下，是需要写tabsLayout 才可以正常显示

请问 tabsLayout  是写在哪里的？ @zozopen

**Comment by zozopen** [comment]
> 

app.tsx里面

**Comment by xiaohuoni** [comment]
感觉你说的不对。装最新的版本，有问题再反馈。
