### ISSUE TITLE
开启多tabs页面后，首次编译登录后会白屏

### ISSUE THREAD

**Issue by zozopen** [alitajs/alita#421]
开启多tabs页面

然后跑编译

登录进入首页

报错且白屏

我估计跟多tabs有关系，就提到这里了

![image](https://user-images.githubusercontent.com/23204297/190983249-cf9f09cb-1476-475e-bea8-e21e25dea0e8.png)

![image](https://user-images.githubusercontent.com/23204297/190944517-b334c96c-60fa-4226-a113-a479e6c62e06.png)

尝试了一下
问题应该是一直重定向导致的

![image](https://user-images.githubusercontent.com/23204297/190983370-7d9b2b7d-8a37-43c3-b500-701c15053a86.png)

**Comment by xiaohuoni** [comment]
看不懂这个和 tabs 有什么关系

**Comment by zozopen** [comment]
> 看不懂这个和 tabs 有什么关系



> 我也不是很懂。。但是我起的新项目，然后一开启就会报错

**Comment by xiaohuoni** [comment]
@zozopen 能不能提供一下重现步骤，我来定位下？

**Comment by zozopen** [comment]
> @zozopen 能不能提供一下重现步骤，我来定位下？

好的

pro create myapp  新建一个项目

yarn 我跑的是yarn


config.ts  文件下面添加以下配置，开启多Tabs页面

keepalive: [/./],
tabsLayout: {},

yarn start 跑项目

浏览器 输入 localhost:8000

进入登录页面

然后直接登录 跳转到首页

就是出现上边的报错信息了

**Comment by zozopen** [comment]
> 

是呀，好多BUG，就是看中这个多tabs才搞上的。。差点就准备选 element-admin 来开发了。。

**Comment by xiaohuoni** [comment]
pro-layout 正在改版，等他调整完，我会处理这些问题。

**Comment by xiaohuoni** [comment]
https://github.com/alitajs/alita/issues/436
