### ISSUE TITLE
开启多 Tabs 页面后，登录后首次编译会报错并白屏，刷新才正常

### ISSUE THREAD

**Issue by Cyan-Xmw** [alitajs/alita#424]
### 🐛 bug 描述
先贴出问题，如标题所示：
登录页面正常：
![image](https://user-images.githubusercontent.com/40554571/191195922-1c4ef9cc-7d68-4515-b5e9-4d321ffeddd2.png)
登录后：
![image](https://user-images.githubusercontent.com/40554571/191196951-0c322d7b-d509-4fb0-8ae5-cfb444ec5e9b.png)
![image](https://user-images.githubusercontent.com/40554571/191197004-ea5c07be-b9c6-46e1-b011-491656ccb51c.png)

一开始我以为是我的代码写得有问题，但经过排查，我去掉多 Tabs 页面后，报错就没有了，由此确定是标签页组件的问题

### 💻 复现代码 | Recurrence code

由于本地开发连接了mysql，因此无法最小重现，只能贴出仓库代码

Github：https://github.com/Cyan-Xmw/react-umi-xmw/blob/Cyan/Xmw_web/src/components/TabsLayout/index.tsx

### 🚑 其他信息
初次编译刷新进入 Tabs 页面，页面排版出现问题：
![image](https://user-images.githubusercontent.com/40554571/191199347-8b8fcfc5-4eb0-4f99-8d9f-8c9696cbefd5.png)
点击别的路由后恢复正常：
![image](https://user-images.githubusercontent.com/40554571/191199014-31357f1e-e151-43df-a7dd-3c24ee8da134.png)

### © 版本信息

- Ant Design Pro 版本: 6.0.0-beta.1
- umi 版本: 4.0.21
- 浏览器环境: Google Chrome
- 开发环境 : windows
- node.js: 16.16.0

**Comment by Cyan-Xmw** [comment]
能把多标签页上的路由信息返回来吗，比如 icon 等信息，目前我看参数是拿不到的，起到虎哥的回复

**Comment by xiaohuoni** [comment]
> 能把多标签页上的路由信息返回来吗
tabs 没管理这个数据，用的就是 routes 上面的数据

**Comment by xiaohuoni** [comment]
Tabs 上没 icon 应该是两个问题吧？还没做这个。有需求可以提个需求单子

**Comment by xiaohuoni** [comment]
https://github.com/alitajs/alita/issues/436
