### ISSUE TITLE
关于多页标签与 pro 组合使用的问题及解决方案

### ISSUE THREAD

**Issue by xiaohuoni** [alitajs/alita#436]
## 登录之后 Something went wrong. 或者登录之后白屏

正常 start 之后 登录 ，重现步骤：退出登录，在首页刷新，重新登录

![image](https://user-images.githubusercontent.com/11746742/194734106-14b44232-bcc2-490d-b0dc-9f111449f892.png)

![image](https://user-images.githubusercontent.com/11746742/194734490-2dccf268-121d-48e5-9be1-76fcb3da62be.png)

重现：再任意页面编写 

```ts
import { history } from '@umijs/max';
history.push('/');
```
解决：alita 中解决 https://github.com/alitajs/alita/pull/437

## 标题和图标丢失，没有国际化

![image](https://user-images.githubusercontent.com/11746742/194750240-e80e93a6-a6cb-42b1-b0f2-aa972ff6b7ba.png)

解决：alita 中解决 https://github.com/alitajs/alita/pull/439

**Comment by xiaohuoni** [comment]
午间休息，下午继续搞

**Comment by xiaohuoni** [comment]
其它问题没有复现到，请安装最新版本，如果还有问题请继续给我发 issues

**Comment by xiaohuoni** [comment]
单独使用 @alita/plugins 的朋友，请更新到 @3.0.18
使用 pro 的朋友，请等待这个PR合并后发包
https://github.com/umijs/umi-presets-pro/pull/7

**Comment by Cyan-Xmw** [comment]
> 单独使用 @alita/plugins 的朋友，请更新到 @3.0.18 使用 pro 的朋友，请等待这个PR合并后发包 [umijs/umi-presets-pro#7](https://github.com/umijs/umi-presets-pro/pull/7)

非常感谢，请问最新的已发包了吗？Pro项目是不是更新umi-presets-pro这个包就可以了

**Comment by xiaohuoni** [comment]
@Cyan-Xmw 可以关注这里 https://github.com/umijs/umi-presets-pro/pull/7

**Comment by xiaohuoni** [comment]
相关问题应该都处理了，还有一个边距问题（关闭打开的时候，有时候视图边距会出现），在pro中处理

**Comment by xingming2020** [comment]
1. 新建项目
```shell
npm i @ant-design/pro-cli -g
pro create demo # 选择umi@4
cd demo
```
2. 修改配置：
```javascript
// config/config.ts
export default {
  // ...

  // 尝试开启多tabs
  keepalive: [/./],
  tabsLayout: {
    hasDropdown: true,
  },

  // https://github.com/ant-design/ant-design-pro/issues/10293#issuecomment-1279673708
  mfsu:{
    strategy: 'normal' 
  }
}
```
3. 启动项目
```shell
npm install
npm start
```

如图，左侧菜单消失了👇

![image](https://user-images.githubusercontent.com/67719106/196922141-8bc5e2eb-c3c3-4234-aa50-c5193f92ace8.png)

**Comment by Hexi1997** [comment]
内容过长，tabs栏不fixed在顶部
![image](https://user-images.githubusercontent.com/66669483/204728455-d3ee4550-74c1-4b91-98de-fc2cc309afd5.png)
