### ISSUE TITLE
Invalid config keys: exportStatic 这个配置咋去掉了

### ISSUE THREAD

**Issue by a354123417** [alitajs/alita#454]
我要把 alitajs 打包的项目部署到非根目录，需要这个配置，因为如果访问到二级路由刷新会 404

**Comment by xiaohuoni** [comment]
umi 还没实现，估计这周四能加上。

另外 刷新会 404 可以试试配置 base

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/pull/9602

**Comment by xiaohuoni** [comment]
> base 和 publicPath 都加上了，还是一样，最后我在 nginx 做了手脚解决了 /666

牛啊牛啊，不过这个issues先留着，我这边也要同步umi的更新

**Comment by a354123417** [comment]
OK

**Comment by xiaohuoni** [comment]
已支持 https://github.com/alitajs/alita/pull/461
