### ISSUE TITLE
antd-pro配置了tabs但是不生效

### ISSUE THREAD

**Issue by Cyan-Xmw** [alitajs/alita#457]
config配置：
![image](https://user-images.githubusercontent.com/40554571/197667374-2d806901-46d4-4ce2-a1b9-4c1bb37a1230.png)
package.json：
![image](https://user-images.githubusercontent.com/40554571/197667480-57f8745f-0506-48cf-849c-7d23c4e1b187.png)

app.tsx就没有配置

 ant-design-pro版本：6.0.0-beta.1

请问虎哥还缺少哪一步，或者说是哪个包没升级导致的

**Comment by xiaohuoni** [comment]
看起来没有，报什么错误？

**Comment by Cyan-Xmw** [comment]
> 看起来没有，报什么错误？

![image](https://user-images.githubusercontent.com/40554571/197668430-db804f9c-0526-4af1-80b1-9dcc1f44f48b.png)

没报错，就不不生效，不知道问题在哪里

**Comment by Cyan-Xmw** [comment]
刷新一下会出来一个，但是再次点击路由就没有了
![image](https://user-images.githubusercontent.com/40554571/197668961-6e6ae4ab-e4e4-4e1b-83d7-e9f25832a71c.png)

**Comment by xiaohuoni** [comment]
这么神奇！

**Comment by cdx0512** [comment]
我也在umi4.0.26版本中遇到了这个问题，锁定4.0.24版本就可以正常使用了

**Comment by Cyan-Xmw** [comment]
> 我也在umi4.0.26版本中遇到了这个问题，锁定4.0.24版本就可以正常使用了

umijs/max降到4.0.24菜单直接出不来了，能看下你的package.json不

**Comment by cdx0512** [comment]
@Cyan-Xmw 
![image](https://user-images.githubusercontent.com/83324891/198202349-5ae4b0d5-956d-4308-9802-5c65282a2a6b.png)

**Comment by Cyan-Xmw** [comment]
> @Cyan-Xmw ![image](https://user-images.githubusercontent.com/83324891/198202349-5ae4b0d5-956d-4308-9802-5c65282a2a6b.png)

算了，还是不行，谢谢了

**Comment by zozopen** [comment]
> 这么神奇！

升级到最新版本的 2.3.25 antd pro component 就会出现这个问题了

**Comment by Cyan-Xmw** [comment]
> > 这么神奇！
> 
> 升级到最新版本的 2.3.25 antd pro component 就会出现这个问题了

![image](https://user-images.githubusercontent.com/40554571/198221135-3c7f849f-e45d-40aa-bc79-0a805cf7c10a.png)
我的是这个版本的，不行，现在还没解决

**Comment by xiaohuoni** [comment]
追不上变动，我等那边处理确定了再修复吧！（捂脸）

**Comment by cdx0512** [comment]
> 追不上变动，我等那边处理确定了再修复吧！（捂脸）

想问一下，tab栏现在支持固定首页不可关闭吗

**Comment by xiaohuoni** [comment]
> > 追不上变动，我等那边处理确定了再修复吧！（捂脸）
> 
> 想问一下，tab栏现在支持固定首页不可关闭吗

支持的，用 updateTab

```
updateTab(location.pathname, {
      icon: <UserOutlined />,
      closable: false,
    });

```

**Comment by cdx0512** [comment]
> > > 追不上变动，我等那边处理确定了再修复吧！（捂脸）
> > 
> > 
> > 想问一下，tab栏现在支持固定首页不可关闭吗
> 
> 支持的，用 updateTab
> 
> ```
> updateTab(location.pathname, {
>       icon: <UserOutlined />,
>       closable: false,
>     });
> ```

是的，我在掘金上看过您写的关于这篇的文章。这么修改后，主页这个标签不可关闭。但是打开其他页面后浏览器刷新，主页就会消失

**Comment by xiaohuoni** [comment]
浏览器刷新肯定会重置状态的，你可以在 runtime 配置里面，把首页的 closable 默认值改成 false

**Comment by Michael-F-Chen** [comment]
> 浏览器刷新肯定会重置状态的，你可以在 runtime 配置里面，把首页的 closable 默认值改成 false

同出上面刷新tab才会出现的问题，版本如下
"@umijs/max": "^4.0.24",
"@ant-design/pro-components": "^2.3.13",

另外请问下，业务要求刷新浏览器/退出重登，tab都还在，并actived 最后actived的那个tab,（切换账号不算，每次重登，还需要验证此刻 列出tab是否有权限）应该是要加持久层，可不可以给我思路，我自己加，大佬挺忙的

**Comment by xu-Aurora** [comment]
> 浏览器刷新肯定会重置状态的，你可以在 runtime 配置里面，把首页的 closable 默认值改成 false

请问你说的这个怎么配置？能说的具体写嘛？

**Comment by cdx0512** [comment]
> > 浏览器刷新肯定会重置状态的，你可以在 runtime 配置里面，把首页的 closable 默认值改成 false
> 
> 请问你说的这个怎么配置？能说的具体写嘛？

这样刷新后还是会丢失，我的实现是app.tsx自定义tab栏配置项。把首页固定写在第一个。这个xiaohuoni作者在掘金写的有教程

**Comment by xu-Aurora** [comment]
> > > 浏览器刷新肯定会重置状态的，你可以在 runtime 配置里面，把首页的 closable 默认值改成 false
> > 
> > 
> > 请问你说的这个怎么配置？能说的具体写嘛？
> 
> 这样刷新后还是会丢失，我的实现是app.tsx自定义tab栏配置项。把首页固定写在第一个。这个xiaohuoni作者在掘金写的有教程

你说的是这个嘛？我试了，不生效
<img width="525" alt="image" src="https://user-images.githubusercontent.com/35291465/207782968-9100eb5e-7770-4456-a8be-ad9cadea651b.png">

**Comment by cdx0512** [comment]
> > > > 浏览器刷新肯定会重置状态的，你可以在 runtime 配置里面，把首页的 closable 默认值改成 false
> > > 
> > > 
> > > 请问你说的这个怎么配置？能说的具体写嘛？
> > 
> > 
> > 这样刷新后还是会丢失，我的实现是app.tsx自定义tab栏配置项。把首页固定写在第一个。这个xiaohuoni作者在掘金写的有教程
> 
> 你说的是这个嘛？我试了，不生效 <img alt="image" width="525" src="https://user-images.githubusercontent.com/35291465/207782968-9100eb5e-7770-4456-a8be-ad9cadea651b.png">

// 自定义tab栏配置项
export const getCustomTabs = () => {
  return ({
    isKeep,
    keepElements,
    navigate,
    dropByCacheKey,
    activeKey
  }: any) => {
    return (
      <div className='runtime-keep-alive-tabs-layout' hidden={!isKeep}>
        <Tabs
          hideAdd
          onChange={(key: string) => {
            navigate(key)
          }}
          activeKey={activeKey}
          type='editable-card'
          onEdit={(targetKey: string) => {
            let newActiveKey = activeKey
            let lastIndex = -1
            const newPanel = Object.keys(keepElements.current)
            for (let i = 0; i < newPanel.length; i++) {
              if (newPanel[i] === targetKey) {
                lastIndex = i - 1
              }
            }
            const newPanes = newPanel.filter((pane) => pane !== targetKey)
            // const newPanes = newPanel
            // newPanes.length &&
            if (newActiveKey === targetKey) {
              if (lastIndex >= 0) {
                newActiveKey = newPanes[lastIndex]
              } else {
                // newActiveKey = newPanes[0]
                newActiveKey = '/welcome'
              }
            }
            dropByCacheKey(targetKey)
            if (newActiveKey !== location.pathname) {
              navigate(newActiveKey)
            }
          }}
        >
          <Tabs.TabPane tab='我的桌面' key='/welcome' closable={false} />
          {Object.entries(keepElements.current).map(
            ([pathname, element]: any) => {
              if (pathname !== '/welcome') {
                return (
                  <Tabs.TabPane
                    tab={element?.name || pathname}
                    key={pathname}
                    closeIcon={
                      activeKey === pathname ? (
                        <IconFont type='icon-guanbi' />
                      ) : (
                        <IconFont type='icon-guanbi' />
                      )
                    }
                  />
                )
              }
            },
          )}
        </Tabs>
      </div>
    )
  }
}

**Comment by cdx0512** [comment]
> > > > 浏览器刷新肯定会重置状态的，你可以在 runtime 配置里面，把首页的 closable 默认值改成 false
> > > 
> > > 
> > > 请问你说的这个怎么配置？能说的具体写嘛？
> > 
> > 
> > 这样刷新后还是会丢失，我的实现是app.tsx自定义tab栏配置项。把首页固定写在第一个。这个xiaohuoni作者在掘金写的有教程
> 
> 你说的是这个嘛？我试了，不生效 <img alt="image" width="525" src="https://user-images.githubusercontent.com/35291465/207782968-9100eb5e-7770-4456-a8be-ad9cadea651b.png">

我是照着一个例子改的，你可以把我完成的这个例子修改下，我写的有点乱。

**Comment by xu-Aurora** [comment]
> > > > > 浏览器刷新肯定会重置状态的，你可以在 runtime 配置里面，把首页的 closable 默认值改成 false
> > > > 
> > > > 
> > > > 请问你说的这个怎么配置？能说的具体写嘛？
> > > 
> > > 
> > > 这样刷新后还是会丢失，我的实现是app.tsx自定义tab栏配置项。把首页固定写在第一个。这个xiaohuoni作者在掘金写的有教程
> > 
> > 
> > 你说的是这个嘛？我试了，不生效 <img alt="image" width="525" src="https://user-images.githubusercontent.com/35291465/207782968-9100eb5e-7770-4456-a8be-ad9cadea651b.png">
> 
> 我是照着一个例子改的，你可以把我完成的这个例子修改下，我写的有点乱。

你是照着哪里的例子改的，能发个链接不，github上直接看的复制的代码很乱

**Comment by cdx0512** [comment]
> > > > > > 浏览器刷新肯定会重置状态的，你可以在 runtime 配置里面，把首页的 closable 默认值改成 false
> > > > > 
> > > > > 
> > > > > 请问你说的这个怎么配置？能说的具体写嘛？
> > > > 
> > > > 
> > > > 这样刷新后还是会丢失，我的实现是app.tsx自定义tab栏配置项。把首页固定写在第一个。这个xiaohuoni作者在掘金写的有教程
> > > 
> > > 
> > > 你说的是这个嘛？我试了，不生效 <img alt="image" width="525" src="https://user-images.githubusercontent.com/35291465/207782968-9100eb5e-7770-4456-a8be-ad9cadea651b.png">
> > 
> > 
> > 我是照着一个例子改的，你可以把我完成的这个例子修改下，我写的有点乱。
> 
> 你是照着哪里的例子改的，能发个链接不，github上直接看的复制的代码很乱
https://juejin.cn/post/7109492504424087566#heading-7

**Comment by xiaohuoni** [comment]
你提到的问题应该不存在，你可以在 pro 官方的 [demo-tabs分支](https://github.com/ant-design/ant-design-pro/tree/demo-tabs)上，重现看看，如果还有异常，请重新提一个新的 issues
