### ISSUE TITLE
ant pro中打开tabslayout后，如何关闭当前的tab页？

### ISSUE THREAD

**Issue by Jeijie** [alitajs/alita#458]
ant pro项目当前页面开启了tabslayout，在页面页面操作表单后，需要跳转到另外页面并把当前的页面关掉，如何当前的页面关闭？

**Comment by xiaohuoni** [comment]
感觉在跳转之后，调用清除缓存可以实现。在跳转到页面之后，调用 `dropByCacheKey('/list')`

**Comment by Jeijie** [comment]
真的可以
