### ISSUE TITLE
[BUG] plugin-maxtabs 在路由重定向时导致页面假死

### ISSUE THREAD

**Issue by fangzhengjin** [alitajs/alita#467]
有如下路由, 当访问`/test`时,会打开两个标签页,其中一个为空,另一个为`/test/list`同时会导致资源使用飙升,页面假死
```js
{
    name: '一级菜单',
    path: 'test',
    routes: [
      { path: '/test', redirect: '/test/list' },
      {
        path: 'list',
        name: '列表页',
        component: 'xxxxxx',
      }
    ]
}
```

**Comment by xiaohuoni** [comment]
redirect 应该已经修过了，你看看你的安装版本是多少？

**Comment by xiaohuoni** [comment]
你可以看下这里 https://github.com/alitajs/alita/blob/master/examples/tabs/.umirc.ts#L25

**Comment by xiaohuoni** [comment]
@fangzhengjin 有简单的 复现 demo 吗，你看这里处理了。https://github.com/alitajs/alita/blob/67bddde75ed07812926d2793fb590314a4bafe25/packages/plugins/templates/keepalive/context.tpl#L113 不管配置是什么 redirect 都是跳过的
