### ISSUE TITLE
keep-alive 模板因为引入 antd 警告

### ISSUE THREAD

**Issue by johanazhu** [alitajs/alita#471]
源码中的 keepalive 的模板文件，即 https://github.com/alitajs/alita/blob/master/packages/plugins/templates/keepalive/context.tpl ，因为引入了 antd-design 的 Tabs, Dropdown，而两者因为版本升级，采用不同的写法而在 console 中警告

- Dropdown  是 4.24.0 升级的用法：https://ant.design/components/dropdown-cn
- Tabs 是 4.23.0 升级的用法：https://ant.design/components/tabs-cn/

**Comment by xiaohuoni** [comment]
只是警告，不好处理。antd 版本最终用的是用户项目中安装的版本，如果改成新的写法，我怕久的版本错误

**Comment by johanazhu** [comment]
> 

嗯嗯，那么能不能加个参数让使用者选择是否新老版本呢

**Comment by chj-damon** [comment]
@johanazhu  目前Tabs的warning已经fix了，Dropdown的PR还没有merge,等发新版了你再试试

**Comment by johanazhu** [comment]
> 

侠之大者，为国为使用者

**Comment by xiaohuoni** [comment]
感谢 @chj-damon 修复，请更新 @alita/plugins@3.2.12 或者 alita@3.2.15
