### ISSUE TITLE
prod mode how custom splash page

### ISSUE THREAD

**Issue by chentianxin** [alitajs/alita#476]
如何自定义启动页面加载动画？
文档上只有个类似的[loading](https://alitajs.com/zh-CN/docs/guides/directory-structure#loadingtsxjsx)

**Comment by xiaohuoni** [comment]
这个要自己写。类似 https://github.com/alitajs/alita/blob/dbf72b0a3bd6a37f99966dd6f1fce02711f85db8/packages/alita/src/features/alitaloading.ts#L10
