### ISSUE TITLE
如何加群

### ISSUE THREAD

**Issue by xiaohuoni** [alitajs/alita#48]
钉钉dingtalk
![image](https://user-images.githubusercontent.com/11746742/64931621-3c39cf80-d86c-11e9-84fe-f86745f71d9b.png)
微信wechat
![image](https://user-images.githubusercontent.com/11746742/64931632-54a9ea00-d86c-11e9-89a7-9e659ccaeefa.png)
微信群失效的话，请添加下面机器人，回复alita进群。
![image](https://user-images.githubusercontent.com/11746742/64931645-71462200-d86c-11e9-8165-bc403cbb9028.png)

**Comment by wangxingkang** [comment]
已添加到README，关闭
