### ISSUE TITLE
[BUG] tabs使用的一些异常

### ISSUE THREAD

**Issue by fangzhengjin** [alitajs/alita#495]
1. dropByCacheKey 无法关闭当前tab(场景为在新建页保存数据后自动关闭新建页)
2. redirect 会多出空白tab且影响渲染(http://localhost:8001/test -> http://localhost:8001/test/list)
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/12680972/208247668-7b5d48f4-8e19-4bb9-858a-f5a6f555e651.png">

3. 页面有footer时, 切换tab依然会显示
<img width="1713" alt="image" src="https://user-images.githubusercontent.com/12680972/208247633-4e0467d3-8593-4e25-bb1a-9f9cd4e88e1e.png">

4. 无法使用CustomTabs, 如果自定义了页面会直接异常
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/12680972/208247557-e9c5ca2e-c97f-445f-9be9-ca2d221a2962.png">

<img width="1715" alt="image" src="https://user-images.githubusercontent.com/12680972/208247572-ba3c208b-a969-4f7a-9388-35d6ccc51aab.png">

---
复现仓库: https://github.com/fangzhengjin/issues-alitajs-495

**Comment by cdx0512** [comment]
使用了query传参，再回到这个路由时参数没了。

**Comment by chj-damon** [comment]
> 1. dropByCacheKey 无法关闭当前tab(场景为在新建页保存数据后自动关闭新建页)

这个需要配合history.push或者navigate，可以实现。我在实际项目中是这么用的。
```tsx
useRequest(saveService, {
    onSuccess() {
      const pathname = location.pathname;
      history.push('/list');
      dropByCacheKey(pathname);
    }
})
```

**Comment by chj-damon** [comment]
> 3\. 页面有footer时, 切换tab依然会显示

这个footer应该跟你的layout有关。tabs本身渲染的内容包括一个标签栏和下面的页面，它们整个是作为layout的content的。目前无法在tab对应的页面里设置footer（PS：你可以用patch-package硬加)

**Comment by chj-damon** [comment]
> 2\. redirect 会多出空白tab且影响渲染(http://localhost:8001/test -> http://localhost:8001/test/list)

redirect目前是不支持的。

**Comment by xiaohuoni** [comment]
你提到的问题应该不存在，你可以在 pro 官方的 [demo-tabs分支](https://github.com/ant-design/ant-design-pro/tree/demo-tabs)上，重现看看，如果还有异常，请重新提一个新的 issues
