### ISSUE TITLE
antd5.x版本控制台会出现警告

### ISSUE THREAD

**Issue by Cyan-Xmw** [alitajs/alita#498]
警告如下：
![image](https://user-images.githubusercontent.com/40554571/211477916-ee588a7d-3650-432d-9cdc-4dfc80637746.png)
![image](https://user-images.githubusercontent.com/40554571/211477948-1f5b4712-fac4-4055-856a-48fa18ebf22d.png)

虎哥，能否做一下 antd 的版本的处理，让4.x和5.x版本都不会出现这种情况，还是支持5.x就行了

**Comment by chj-damon** [comment]
tabs的warnning提示已经修复了，dropdown的提了PR，还没merge

**Comment by xiaohuoni** [comment]
你提到的问题应该不存在，你可以在 pro 官方的 [demo-tabs分支](https://github.com/ant-design/ant-design-pro/tree/demo-tabs)上，重现看看，如果还有异常，请重新提一个新的 issues
