### ISSUE TITLE
[ Fearture ] 切换多语言时，标签页无法响应

### ISSUE THREAD

**Issue by Cyan-Xmw** [alitajs/alita#499]
![image](https://user-images.githubusercontent.com/40554571/211501499-faf58f54-08ff-4f27-bb6c-a2a2bd2ea24b.png)
 提个 Fearture，能实现最好了，不行也没关系，哈哈

**Comment by xiaohuoni** [comment]
应该是支持的，你是不是没写对，哈哈哈

**Comment by Cyan-Xmw** [comment]
> 应该是支持的，你是不是没写对，哈哈哈

我肯定是写对的，不对的话标签的中文也不会显示，我是写在BasiLayout的onPageChange方法里面的，换到别的地方也不行，所以我就感觉是组件内部的问题，暂时找不到原因，虎哥有空可以测一下

**Comment by chj-damon** [comment]
@Cyan-Xmw  多语言支持这个功能应该前不久已经上线了，可以重新用新版本看看

**Comment by xiaohuoni** [comment]
你提到的问题应该不存在，你可以在 pro 官方的 [demo-tabs分支](https://github.com/ant-design/ant-design-pro/tree/demo-tabs)上，重现看看，如果还有异常，请重新提一个新的 issues
