### ISSUE TITLE
希望 updateTab 能支持 TabsItem 的所有属性，或者单独支持 size 属性

### ISSUE THREAD

**Issue by Cyan-Xmw** [alitajs/alita#501]
希望 updateTab 能支持 TabsItem 的所有属性，或者单独支持 size 属性
![image](https://user-images.githubusercontent.com/40554571/211696920-8109101e-191a-4120-b980-41b2b4e52f06.png)

**Comment by xiaohuoni** [comment]
这个api 是修改单个tab 的配置的，在这里传入影响所有 tab 的属性，感觉是不对的？

**Comment by xiaohuoni** [comment]
@Cyan-Xmw 已支持，详细用法见文档 https://alitajs.com/zh-CN/docs/guides/tabs

**Comment by Cyan-Xmw** [comment]
> @Cyan-Xmw 已支持，详细用法见文档 https://alitajs.com/zh-CN/docs/guides/tabs

好的，谢谢虎哥，这个是直接更新umi的包就生效了吗

**Comment by xiaohuoni** [comment]
@Cyan-Xmw 你没使用 alita 的话，应该是更新 @alita/plugins@3.2.9
