### ISSUE TITLE
提示keep-alive找不到@/app，重新install无效

### ISSUE THREAD

**Issue by wojoc** [alitajs/alita#502]
**umi3.5.36 使用@alitajs/keep-alive**
import * as app from '@/app';
提示找不到@/app
![image](https://user-images.githubusercontent.com/65233821/211999556-d2e3ca1b-84af-4fc2-808a-cb8ab8bbd252.png)

- umi 3.5.36:
- node v16.16.0:

**Comment by wojoc** [comment]
> tsconfig 配置对不对？
paths我也排查过
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "esnext",
    "target": "esnext",
    "lib": ["esnext", "dom"],
    "sourceMap": true,
    "baseUrl": ".",
    "jsx": "preserve",
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "allowJs": true,
    "skipLibCheck": true,
    "experimentalDecorators": true,
    "strict": true,
    "paths": {
      "@/*": ["./src/*"],
      "@@/*": ["./src/.umi/*"]
    }
  },
  "include": [
    "mock/**/*",
    "src/**/*",
    "tests/**/*",
    "test/**/*",
    "__test__/**/*",
    "typings/**/*",
    "config/**/*",
    ".eslintrc.js",
    ".stylelintrc.js",
    ".prettierrc.js",
    "jest.config.js",
    "mock/*"
  ],
  "exclude": ["node_modules", "build", "dist", "scripts", "src/.umi/*", "webpack", "jest"]
}

**Comment by xiaohuoni** [comment]
直接给个复现 demo 吧

**Comment by wojoc** [comment]
> 直接给个复现 demo 吧

稍等，我马上去准备，可能需要点时间，但其实目前遇到的就只是这一行代码找不到依赖.
![image](https://user-images.githubusercontent.com/65233821/212030017-edf457f3-8faf-4161-9aa3-832196f74b0c.png)

**Comment by wojoc** [comment]
> 直接给个复现 demo 吧
再准备复现的时候，我建了新的AntD pro项目，在src底下生成了一个app.tsx文件，老版本是没有的
新版本
![image](https://user-images.githubusercontent.com/65233821/212227109-5590a6cb-9290-4656-8a43-7f58d61a2b91.png)
老版本
![image](https://user-images.githubusercontent.com/65233821/212227165-80bfd255-e0a9-4dc3-bf48-dbf211367479.png)
是版本不一致的问题吗，结合我这边的另一台电脑，他是 "@alitajs/keep-alive": "^2.8.31",
![image](https://user-images.githubusercontent.com/65233821/212227262-7b439c3d-0170-4213-b83a-45086cb93274.png)

是没有生成import * as app from '@/app';这一句话的
我这边版本"@alitajs/keep-alive": "^2.9.0",是有的
![image](https://user-images.githubusercontent.com/65233821/212227485-74e181af-3917-40d0-8568-a3d247bb3925.png)

在src目录下建空文件夹app.tsx 就没有报错信息

**Comment by wojoc** [comment]
> "@alitajs/keep-alive": "^2.9.0"

指定安装2.8.31已解决

**Comment by xiaohuoni** [comment]
增加了运行时配置，umi 项目应该都有 app 文件，作为运行时配置文件。脚手架没新建就自己新建一个，2.x 的版本内容，非必要不更新。

**Comment by cangsnage** [comment]
> > "@alitajs/keep-alive": "^2.9.0"
> 
> 指定安装2.8.31已解决

我想问下keepalive 的配置是在config.ts 里面配置么
