### ISSUE TITLE
【Bug】跳转有重定向的路由，页面会陷入死循环

### ISSUE THREAD

**Issue by Cyan-Xmw** [alitajs/alita#503]
问题截图：
![image](https://user-images.githubusercontent.com/40554571/212607397-eb5705b0-ce89-412a-ba46-5e8d9fc3ec67.png)

复现步骤：
官方 Demo 点击面包屑的管理页跳转到重定向路由：
![image](https://user-images.githubusercontent.com/40554571/212607797-a117cc1d-618f-4dd9-89ff-da3d29a4da5a.png)

**Comment by xiaohuoni** [comment]
状态保持页面，不支持跳转。因为新的跳转也是一个组件。

**Comment by chj-damon** [comment]
redirect目前不支持
