### ISSUE TITLE
[多tabs] hasFixedHeader 表现和样式在 demo 错误

### ISSUE THREAD

**Issue by xiaohuoni** [alitajs/alita#506]
当前主分支
```bash
pnpm build
cd examples/tabs
pnpm dev
```

![image](https://user-images.githubusercontent.com/11746742/215371035-073815c1-12de-4c47-b8bd-c102e2d633d1.png)

**Comment by xiaohuoni** [comment]
@Hexi1997 cc

**Comment by Hexi1997** [comment]
> @Hexi1997 cc

收到，我今天找时间看一下，看起来像是布局问题

**Comment by xiaohuoni** [comment]
嗯，记得更新一下主分支先，我调整了一些 tpl （更复杂了）
