### ISSUE TITLE
tabs配合键盘事件的问题

### ISSUE THREAD

**Issue by wuranxu** [alitajs/alita#514]
#### bug描述:
  多页签在非active的tab页仍然能激活键盘事件。
#### 前置条件:
  开了多个页面a和b，当前处于a页面，b页面使用ahooks的`useKeyPress`监听了键盘事件弹出modal
#### 预期结果:
  在a页面`不弹出`b页面的modal
#### 实际结果:
  在a页面`弹出`了b页面的modal

看了`ahooks`好像没有类似的api解决，只能麻烦虎哥了！

如果在其他页面弹还能接受，我是一个页面不同的id，等于是会有多个相同的页面，按下快捷键就会弹出N个modal，而且modal还是在当前图层，尴尬= =

**Comment by xiaohuoni** [comment]
不用尴尬，在 响应里面加上当前的 pathname 判断，就可以了吧？

**Comment by wuranxu** [comment]
> 不用尴尬，在 响应里面加上当前的 pathname 判断，就可以了吧？

听起来是可以的，就是实践起来发现自己只知道window.location.pathname，拿不到当前active的tab path，虎哥可以给个相关文档么，我发现这个项目好像不是tabs的项目，我好像问错地方了（已star）

**Comment by wuranxu** [comment]
> > 不用尴尬，在 响应里面加上当前的 pathname 判断，就可以了吧？
> 
> 听起来是可以的，就是实践起来发现自己只知道window.location.pathname，拿不到当前active的tab path，虎哥可以给个相关文档么，我发现这个项目好像不是tabs的项目，我好像问错地方了（已star）

解决了，找到一种最辣鸡的方法:
在useKeyPress hook里面判断window.location.href  是否等于 /xxxx/xxxx/ +当前的页面id 
谢谢虎哥！

**Comment by xiaohuoni** [comment]
🌹
