### ISSUE TITLE
1、【BUG】国际化报错。2、【BUG】后台请求的动态菜单（路由）所有的TABS失效。3、【需求】V6tabs不存在关闭其他，关闭全部这种按钮。4、【需求】设置动态路由（路由配置存在某个参数，控制当前组件是否缓存）

### ISSUE THREAD

**Issue by scepter0430** [alitajs/alita#517]
1、
![abe4777f4e179ea5a8f5e2cad1fd20d](https://user-images.githubusercontent.com/63215136/218893748-879a04eb-e426-4bf1-8749-e0319e807ef7.png)

2、
![7e70b9bf383977f1c746c1c0b6e536c](https://user-images.githubusercontent.com/63215136/218893781-4c8581d5-b5b5-4285-9ee1-75e32e110aaa.png)

3、
![cd540abba3fbd822b6514f190645cca](https://user-images.githubusercontent.com/63215136/218893815-1cac7e79-a80e-410b-8159-06d5e7242ffb.png)

**Comment by xiaohuoni** [comment]
你提到的问题应该不存在，你可以在 pro 官方的 [demo-tabs分支](https://github.com/ant-design/ant-design-pro/tree/demo-tabs)上，重现看看，如果还有异常，请重新提一个新的 issues
