### ISSUE TITLE
dropByCacheKey方法失效

### ISSUE THREAD

**Issue by SunshineH2** [alitajs/alita#522]
用的alita的keepalive的插件，想要在完成某个动作时关闭当前页面，调用了
`
import { KeepAliveContext } from '@umijs/max';
const { dropByCacheKey } = useContext<any>(KeepAliveContext)
dropByCacheKey('/list')
`
但是没有成功关闭tab

@alita/plugins 版本是3.2.10和3.2.11，都不生效
@umijs/max的版本是4.0.12

**Comment by chj-damon** [comment]
history.back() 不行，history.push和navigate可以
