### ISSUE TITLE
Keep Alive

### ISSUE THREAD

**Issue by xiaohuoni** [alitajs/alita#53]
项目紧急需求，umi 一直没进展，先在alita中实现使用。
如果可以写成插件。
https://github.com/umijs/umi/pull/3084

**Comment by xiaohuoni** [comment]
keepalive:['/list','/xxx']

**Comment by xiaohuoni** [comment]
写在配置中的会被保留，只能手动触发解除。

**Comment by xiaohuoni** [comment]
使用之前，或者更新 umi 之后，都需要手动执行 `umi keepalive` 进行初始化

**Comment by wangyinwei1** [comment]
什么时候能合并啊，现在急需keepalive

**Comment by xiaohuoni** [comment]
@wangyinwei1 你用alita的话，现在已经具备了keep alive的能力了。

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/15857725/67646020-ff7eef00-f966-11e9-9e7d-73b0b515a81c.png)
![image](https://user-images.githubusercontent.com/15857725/67646029-09085700-f967-11e9-9d0e-35b6fa52c0e7.png)
请问我这个是哪配置错了吗？安装你上面的步骤配置的，但是启动报错了

**Comment by xiaohuoni** [comment]
@wangyinwei1 在这里讨论把

**Comment by xiaohuoni** [comment]
不是执行yarn init 是执行yarn run init （umi keepalive）

**Comment by wangyinwei1** [comment]
> @wangyinwei1 你用alita的话，现在已经具备了keep alive的能力了。

刚了解了umi,现在又多了一个alita，我想了解下，做pc端，那么我该怎么选择？可以列下alita的最大的优点吗？

**Comment by wangyinwei1** [comment]
> @wangyinwei1 你用alita的话，现在已经具备了keep alive的能力了。

@xiaohuoni 刚了解了umi,现在又多了一个alita，我想了解下，做pc端，那么我该怎么选择？可以列下alita的最大的优点吗？

**Comment by wangyinwei1** [comment]
![que](https://user-images.githubusercontent.com/15857725/67828556-ced9b980-fb0e-11e9-9d19-daaf2018d2dd.gif)
嵌套路由之间的切换缓存不了数据，同级切换可以缓存，这个是什么原因@xiaohuoni

**Comment by CJY0208** [comment]
估计是嵌套路由的链路没有全部是 CacheRoute ...

[这个 issues](https://github.com/CJY0208/react-router-cache-route/issues/45#issuecomment-534947665) 有提到，umi 里路由不可控，估计比较难搞了

**Comment by xiaohuoni** [comment]
@wangyinwei1 看一下你的设置

**Comment by xiaohuoni** [comment]
嵌套路由内部跳转可以，跳转到其他路由，不行。
讨论一下

**Comment by my937889621** [comment]
根据readme使用里面的方法配置约定式路由时不生效，配置式路由时报错
```
×  error     Plugin user:node_modules/umi-plugin-cache-route/lib/index.js initialize failed

Cannot read property 'keepalive' of undefined
```
最终结合两种方案一起才生效..

**Comment by xiaohuoni** [comment]
找不到要升级 alita 版本

**Comment by my937889621** [comment]
> 找不到要升级 alita 版本

我没用alita，是根据https://github.com/umijs/umi/issues/3091这里放到umi里使用

**Comment by rule78** [comment]
现在umi项目 还不能使用对吧 Cannot read property 'keepalive' of undefined

**Comment by xiaohuoni** [comment]
哦，可以使用的，就是嵌套路由互相跳转不生效，正在处理。
使用方法你要安装[umi-plugin-cache-route](https://www.npmjs.com/package/umi-plugin-cache-route)

**Comment by wangyinwei1** [comment]
嵌套路由互相跳转不生效,这个修改好了吗？

**Comment by xiaohuoni** [comment]
还没有

**Comment by wangyinwei1** [comment]
嵌套路由互相跳转不生效，请问是有技术困难？会准备搁置吗？还是在计划中？

**Comment by CJY0208** [comment]
> 嵌套路由互相跳转不生效，请问是有技术困难？会准备搁置吗？还是在计划中？

目前项目比较忙，还未进行方案讨论，技术上的预想有一定难度

处于计划中，不会搁置

**Comment by xiaohuoni** [comment]
嵌套路由的方式，可以先通过配置修复。
```js
export default {
  plugins: [
    ['umi-plugin-cache-route', {
      keepalive:['/list','/list/abc']
    }],
  ],
}
```

**Comment by xiaohuoni** [comment]
https://github.com/alitajs/alita/pull/57

**Comment by xiaohuoni** [comment]
太长了，还有问题的话，另开issues吧

**Comment by wangyinwei1** [comment]
#64 umi-plugin-cache-route@2.0.0 会有一个报错警告。是什么原因。@xiaohuoni
