### ISSUE TITLE
ReferenceError: VerticalRightOutlined is not defined useKeepOutlets ./src/.umi/plugin-keepalive/context.tsx:252

### ISSUE THREAD

**Issue by hui-huo** [alitajs/alita#542]
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/55521126/225529122-4b18ad9e-1e29-45e0-86e7-1013fbac03b8.png">
<img width="460" alt="image" src="https://user-images.githubusercontent.com/55521126/225529255-76efb0b1-224d-4abb-b7c8-92d0c311a57b.png">

如图，.umi的keepalive少导入了VerticalRightOutlined，谢谢

**Comment by xiaohuoni** [comment]
应该用到自定义 tabs 不需要 item ？

**Comment by Cyan-Xmw** [comment]
![image](https://user-images.githubusercontent.com/40554571/225532262-75ae10f4-fd04-48ed-b614-8361305446cb.png)
我也遇到这个问题

**Comment by xiaohuoni** [comment]
已修复，等我发个版本。

**Comment by xiaohuoni** [comment]
info  - + @alita/plugins 3.2.18
info  - + alita 3.2.22

**Comment by hui-huo** [comment]
🐂，但这个好奇怪，我试着安装了旧版本的也会报错，刚接触还以为是我自己的问题，抱着试一试的心态问问 😄

**Comment by xiaohuoni** [comment]
嗯，是因为这里的提交导致的错误 https://github.com/alitajs/alita/pull/521 我们没有自定义 tabs 所以没验证到错误。
我加了个 ci 来做这个事情，保证后续代码的正确性。

**Comment by Cyan-Xmw** [comment]
> alita

虎哥，这个更新的包合到 umi 上了吗，是更新 umi 的包就行了吗，我现在更新还不行
