### ISSUE TITLE
设置 publicPath 的情况，部分文件没带带上路径

### ISSUE THREAD

**Issue by xiexingen** [alitajs/alita#547]
<img width="612" alt="error" src="https://user-images.githubusercontent.com/7939085/226175217-618f0899-29e2-4e24-879e-d0a704e3a4df.png">

配置文件如下:
{
  runtimePublicPath: {},
  publicPath:process.env.NODE_ENV==='production'?'/member/':'/',
  // publicPath:'/',

  appType: 'h5',
  // keepalive: [/users/],
  // aconsole: {
  //   console: {},
  //   inspx: {},
  // },
  // theme: { '@primary-color': '#1DA57A' },
  mobileLayout: 'mobile5',
  mfsu: {},
  history: {
    type: 'hash',
  },
  hash: true,
  npmClient: 'pnpm',
  ignoreMomentLocale: true,
  targets: {
    ie: 11,
  },
  exportStatic: {},
  lessLoader: {
    javascriptEnabled: true,
  },

**Comment by xiaohuoni** [comment]
开启 runtimePublicPath 之后，window.publicPath 配置了吗？

```ts
<head>
  <script>
    window.publicPath = '/foo/'
  </script>
</head>
```

详见文档 https://alitajs.com/zh-CN/docs/config/config#runtimepublicpath
