### ISSUE TITLE
PageContainer存在footer组件时切换tab显示异常

### ISSUE THREAD

**Issue by wuranxu** [alitajs/alita#552]
先说好这个问题不知道算不算tabsLayout的，但是我`感觉`是的！！！

前置条件:
准备2个页面，均由PageContainer包裹，其中一个添加footer元素如下图:
![image](https://user-images.githubusercontent.com/11266738/226617351-8e70ae71-1d87-40af-a7f8-d5cbee4b7789.png)

重现方式:
同时打开2个页面，会发现2个页面都会显示了footer，实际上只有1个页面`存在footer`。
![image](https://user-images.githubusercontent.com/11266738/226618988-70e63826-fc6e-4456-866e-13a4edebf009.png)

我尝试了判断window.location.href确定是否显示footer，但据观察下来不起作用T.T
![image](https://user-images.githubusercontent.com/11266738/226618681-4db25f7e-65a5-4028-b7cf-5780201024ef.png)

**Comment by xiaohuoni** [comment]
能不能给一个可以运行起来的仓库？

**Comment by wuranxu** [comment]
> 能不能给一个可以运行起来的仓库？

[demo项目](https://github.com/wuranxu/tabs-demo)

因为codesandbox太麻烦了，不适合antd pro，就建了个仓库，麻烦虎哥看一下哈。
目前welcome页面有footer，其它页面都没有，切换的时候其他页面的footer`不会消失`。

![image](https://user-images.githubusercontent.com/11266738/226860892-d0245c44-70ed-47e0-87a6-36a3e91643e2.png)

**Comment by xiaohuoni** [comment]
先说结论，不是 tabs 的问题，你可以先这么写

```tsx
const Welcome: React.FC = () => {
  const location = useLocation();
  return (
    <PageContainer
      footer={[<Button type="primary">虎哥辛苦</Button>]}
      footerToolBarProps={{ style: location.pathname !== '/welcome' ? { display: 'none' } : {} }}
    >
    </PageContainer>
  );
};

export default Welcome;
```

如何复现这个问题？

```tsx
import { PageContainer } from '@ant-design/pro-components';
import { Button } from 'antd';
import React, { useState } from 'react';

const Welcome: React.FC = () => {
  const [hidden, setHidden] = useState(false);
  return (
    <>
      <Button
        onClick={() => {
          setHidden(!hidden);
        }}
      >
        Click me!
      </Button>
      <div hidden={hidden}>
        <PageContainer footer={[<Button type="primary">虎哥辛苦</Button>]}>
          {Math.random()}
        </PageContainer>
      </div>
    </>
  );
};

export default Welcome;

```
如何解？不知道我还在解。

**Comment by wuranxu** [comment]
好的，谢谢帅气的虎哥！~我就想肯定不是tabs的问题！

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/227192852-a61e182f-7051-439d-ae4b-30de8891bb5a.png)
![image](https://user-images.githubusercontent.com/11746742/227192889-31f29812-7ae8-4db2-b79f-ed5f3d664bbc.png)
