### ISSUE TITLE
最新版本 antd pro 开启多tabs报错

### ISSUE THREAD

**Issue by zozopen** [alitajs/alita#553]
![image](https://user-images.githubusercontent.com/23204297/229021915-aaa6bc0e-1b3f-4253-a416-035fa852a127.png)

  keepalive: [/./],
  tabsLayout: {}, 

已经开启这两个

这问题好像很久了。。

**Comment by zozopen** [comment]
看了一下，最新版没有集成了，需要单独添加
   require.resolve('@alita/plugins/dist/keepalive'),
    require.resolve('@alita/plugins/dist/tabs-layout'),

**Comment by xiaohuoni** [comment]
有的吧，是不是你没有用 [umi-presets-pro](https://github.com/umijs/umi-presets-pro) ？
