### ISSUE TITLE
无法使用 UMI_ENV 环境变量

### ISSUE THREAD

**Issue by lwQin** [alitajs/alita#554]
无法使用 UMI_ENV 环境变量根据不同环境编译生产对应产物

**Comment by xiaohuoni** [comment]
你是怎么用的？

**Comment by xiaohuoni** [comment]
注：根据当前环境的不同，dev, prod, test 配置文件会自动加载，不能将 UMI_ENV 的值设定成他们。
https://umijs.org/docs/guides/env-variables#umi_env
