### ISSUE TITLE
切换用户登录后，如何能不自动打开前一个用户打开的所有标签页

### ISSUE THREAD

**Issue by cui-xxu** [alitajs/alita#559]
不同用户可能有不同的权限，自动看到前一个用户打开的所有标签页不合适。
我看代码，应该是keepElements记录了所有打开的标签页，但是没找到将其清空的方法

**Comment by cui-xxu** [comment]
const kaContext = useContext(KeepAliveContext);
  kaContext.keepElements.current = [];
我从登录组件直接做了个清空，貌似有效，不知道有没有什么隐患啊

**Comment by xiaohuoni** [comment]
这样可以。也可以调用 close all ，操作是一样的
