### ISSUE TITLE
那里有umi-plugin-cache-route的源码

### ISSUE THREAD

**Issue by flyingFlowers** [alitajs/alita#56]
想学习一下大神keep-alive的操作，
包中的代码都编译过了，读着实在难受，哪里有源码

**Comment by xiaohuoni** [comment]
在umi的分支 https://github.com/umijs/umi/pull/3084

**Comment by xiaohuoni** [comment]
具体实现是 https://github.com/CJY0208/react-router-cache-route umi 分支上也是根据他的用例编写的

**Comment by inTheSun** [comment]
想咨询下，能把umi里面的CacheRoute中的when参数暴露出来吗？

**Comment by xiaohuoni** [comment]
这个还存在嵌套路由的问题，后续修复了这个问题之后，会修改这个入参。
@CJY0208

**Comment by inTheSun** [comment]
> 这个还存在嵌套路由的问题，后续修复了这个问题之后，会修改这个入参。
> @CJY0208

谢啦

**Comment by xiaohuoni** [comment]
这个方案暂时废弃了，请使用umi-pluin-keep-alive
