### ISSUE TITLE
umi使用多页签不生效

### ISSUE THREAD

**Issue by mwj610** [alitajs/alita#560]
![image](https://user-images.githubusercontent.com/52907799/233017754-03bfff2a-8b25-483f-9ffa-584d654de05b.png)

![image](https://user-images.githubusercontent.com/52907799/233017244-ab7006d5-55de-4561-a2da-e16527ce7590.png)

![image](https://user-images.githubusercontent.com/52907799/233017289-fbe3ef8e-c8b9-4ef7-95a7-ec77dd0019b5.png)

**Comment by xiaohuoni** [comment]
自定义使用，要用  `useKeepOutlets();` 替代 `useOutlets`
可以参考这里 https://github.com/alitajs/alita/blob/12e4d9dd5ff9171f1288f03fcdc246b32e8ecc60/examples/tabs/src/layouts/index.tsx#L33
