### ISSUE TITLE
[feature] tabBar-list 中的item 如何做权限控制

### ISSUE THREAD

**Issue by xiexingen** [alitajs/alita#563]
比如张三有权限看到4个
![image](https://user-images.githubusercontent.com/7939085/233643548-6540f53b-7826-4b25-b270-421ef189e630.png)

而另外的账户没有其中的某个权限，目前控制不到。
ps: 看setTabBarList的实现方式也是 merge
![image](https://user-images.githubusercontent.com/7939085/233643919-23cba1b6-ab2d-440d-9033-54e5f5eb3f20.png)

**Comment by xiaohuoni** [comment]
设置 remove 为 true 可以移除
