### ISSUE TITLE
keepalive 模板中有个bug

### ISSUE THREAD

**Issue by johanazhu** [alitajs/alita#569]
报错信息如下：
Cannot read properties of undefined (reading 'toLowerCase')

所属代码块：
https://github.com/alitajs/alita/blob/master/packages/plugins/templates/keepalive/context.tpl#L148

**Comment by xiaohuoni** [comment]
怎么复现呢？看起来都是字符串

**Comment by johanazhu** [comment]
> 怎么复现呢？看起来都是字符串

就把 ant-design-pro + qiankun 的项目升级到最新版（引用了keep-alive）就报错了
报错信息如下：
![image](https://github.com/alitajs/alita/assets/24203037/883cd1f4-8beb-4c75-a0ad-583cd8fe1fbf)
当我调试时，成这样：
![image](https://github.com/alitajs/alita/assets/24203037/795620cb-1077-46fe-b113-5ee8ff3dc832)

把 `const fullPath = getFullPath(item.path?.toLowerCase(), parentPath?.toLowerCase());` 就可以了

**Comment by xiaohuoni** [comment]
可是 item.path 为什么为 undefined？

**Comment by xiaohuoni** [comment]
info  - + @alita/plugins 3.2.22
info  - + alita 3.2.27

这个版本先规避了，但是还是希望跟进 tem.path 为什么为 undefined

**Comment by johanazhu** [comment]
> info - + @alita/plugins 3.2.22 info - + alita 3.2.27
> 
> 这个版本先规避了，但是还是希望跟进 tem.path 为什么为 undefined

嗯嗯，我再查查是啥原因

**Comment by johanazhu** [comment]
> 

找到原因了，如果在 `conf/routes.ts` 中配置404 页面，也就是  { component: './404' }，当没有 path 参数，访问 item.path 自然是 undefined

**Comment by xiaohuoni** [comment]
ok，那就明白了，更新版本就可以。🌹

**Comment by johanazhu** [comment]
> ok，那就明白了，更新版本就可以。🌹

🌹🌹
