### ISSUE TITLE
升级 Umi 相关依赖的版本

### ISSUE THREAD

**Issue by fz6m** [alitajs/alita#579]
目前由于 umi 最新版本已经是 esbuild `0.17.19` 了，但是 alita 这里锁了 umi 版本，依赖的是 esbuild `0.16.17` 。

因为 ant pro 的预设 `umi-presets-pro` 依赖了 `@alita/plugins` ，所以多了份 umi 的依赖，导致 esbuild 两份，版本冲突了，之前 ant pro 也发生过一次。

<img src='https://github.com/alitajs/alita/assets/59400654/39153054-243c-44cd-bc1e-fce8091a6120' width='40%' />

所以 alita 这边该升级依赖的 umi 版本了。

**Comment by lovewinders** [comment]
> 目前由于 umi 最新版本已经是 esbuild `0.17.19` 了，但是 alita 这里锁了 umi 版本，依赖的是 esbuild `0.16.17` 。
> 
> 因为 ant pro 的预设 `umi-presets-pro` 依赖了 `@alita/plugins` ，所以多了份 umi 的依赖，导致 esbuild 两份，版本冲突了，之前 ant pro 也发生过一次。
> 
> <img alt="" width="40%" src="https://user-images.githubusercontent.com/59400654/244434059-39153054-243c-44cd-bc1e-fce8091a6120.png">
> 所以 alita 这边该升级依赖的 umi 版本了。

我这也碰到这个问题，linux上采用pnpm install就会报错 Error: Expected "0.17.19" but got "0.16.17"

**Comment by lovewinders** [comment]
@xiaohuoni

**Comment by xiaohuoni** [comment]
@fz6m 可以私聊我，或者圈我一下，github 的消息爆炸，很容易漏 issues

**Comment by xiaohuoni** [comment]
@alita/plugins@3.3.1
