### ISSUE TITLE
需要移动端的图表库

### ISSUE THREAD

**Issue by xiaohuoni** [alitajs/alita#59]
实际应用中，发现，alitajs更多的被用于移动端开发。
在做可视化展示的时候，需要配套的图表库或者图表组件使用。

发现一个https://github.com/antvis/f2 ，但似乎图表库比较少
需要更丰富的图表库，或者自己补充组件。

**Comment by chj-damon** [comment]
echarts

**Comment by xiaohuoni** [comment]
https://github.com/alitajs/hd-charts/issues/1
