### ISSUE TITLE
chalk 在浏览器打印图片怎么一直不显示呀

### ISSUE THREAD

**Issue by wen2go** [alitajs/alita#609]

**Comment by xiaohuoni** [comment]
怎么写的？

**Comment by wen2go** [comment]
换成什么图片都是空白的&nbsp; &nbsp;我以为是浏览器版本的问题，我特意让低版本的朋友试了也不行耶&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月20日(星期三) 下午3:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alitajs/alita] chalk 在浏览器打印图片怎么一直不显示呀 (Issue #609)





 
怎么写的？

**Comment by wen2go** [comment]
> 怎么写的？

![image](https://github.com/alitajs/alita/assets/52733748/45a312b0-35e6-4ee7-8e19-4849a0e8b514)

**Comment by xiaohuoni** [comment]
不懂为啥
```
console.log('%c ','background-image:url("http://iyeslogo.orbrand.com/150902Google/005.gif");background-size:120% 120%;background-repeat:no-repeat;background-position:center center;line-height:60px;padding:30px 120px;');

```
