### ISSUE TITLE
这个轮子，这个是干吗用的？

### ISSUE THREAD

**Issue by kaoding** [alitajs/alita#61]
是做一个移动版本的 pro-layout 吗？

**Comment by xiaohuoni** [comment]
pro-layout 在 https://github.com/alitajs/alita-layout 
对于这个轮子是干啥的，它是一个umi的配置简化的脚手架框架。
在介绍什么是alitajs社区的时候，我有简要的介绍了一下alita
https://zhuanlan.zhihu.com/p/92443373
可以看看

**Comment by wangxingkang** [comment]
我觉得是对 umi的一个补充，嘻嘻，加一些解决方案

**Comment by kaoding** [comment]
1、如果是对umi的补充，直接给umi框架提pr，现在umi也有了umi ui
2、如果是做一个移动版本的pro-layout，这个需求是存在，移动组件有mobile.ant.design（还有其它的）
3、为ant.design做一些扩展组件（如：常用的小组件，通用的业务组件），这个需求也是很好的
4、为RN打包的事，自我感觉必要性不是很大，可能你们公司内部用了这个，有这个需求，但这个做为了通用的开源不是特别好。

**Comment by kaoding** [comment]
ant-design-plus，alita-layout 这种就比较好。

**Comment by xiaohuoni** [comment]
应该是我们的问题，经常把alita框架和alitajs社区混在一起。其实你说的很多东西都是社区团队做的事情。alita的核心或者说他的受众是非专业的前端开发人员。所有的方案都刻意的避开了大前端的概念，目的就是为了能让他们，快速的上手业务开发。其实这很大程度上和我们部门的历史包袱有很大的原因。我觉得你说的很对，欢迎加入alitajs社区，一起讨论。
另外，其实它不是对umi的补充。确实更多的补充，都是通过umi的pr来修改的。说是丰富umi的插件市场倒是比较合适。有很多有需求但不通用的东西，并没办法放到umi中去。

**Comment by xiaohuoni** [comment]
关于alita的定位，这个问题非常值得我们一起思考。我的想法就是希望在业务开发中能有更多的low code 或者叫做页面内容配置。

**Comment by kaoding** [comment]
非专业的前端开发人员，这个定位有问题，就比如我吧，我不算是专业前端，也算半个专业前端，我都搞的半天不知道这个要做什么，非专业的前端就更不知道了。umi不是专业前端的本生就很难搞的懂，这个还架接在他上面，就更搞的懂了。

**Comment by xiaohuoni** [comment]
不是告诉你要做什么，而是希望你什么也不要做。这个和umi的设计理念应该是近似的。

**Comment by xiaohuoni** [comment]
很多都还是理想化状态的概念，我们会慢慢的完善和补充。希望它有这个能力，可能他也没有。
