### ISSUE TITLE
closeTab 方法报错，没有正确引入 message

### ISSUE THREAD

**Issue by baiwumm** [alitajs/alita#621]
![image](https://github.com/alitajs/alita/assets/40554571/fb73c0fe-d3a4-42d8-b37b-be3501a10fa6)

**Comment by xiaohuoni** [comment]
复现条件是啥？ antd@5？

**Comment by xiaohuoni** [comment]
@CodeYHJ  hasCustomTabs 应该需要自己定义 tabs ，怎么会走到这里？有没有复现 demo 提供一个

**Comment by CodeYHJ** [comment]
> @CodeYHJ hasCustomTabs 应该需要自己定义 tabs ，怎么会走到这里？有没有复现 demo 提供一个

与keep-alive插件无关，是我们项目上配置 hasCustomTabs 错误的问题
