### ISSUE TITLE
umi-plugin-cache-route 插件bug

### ISSUE THREAD

**Issue by wangyinwei1** [alitajs/alita#64]
![image](https://user-images.githubusercontent.com/15857725/71136331-7639b980-223f-11ea-8e01-9577323f21b1.png)
开始操作，切换同级路由不会报错，一旦切换嵌套的路由就报出这样的一个警告！，请问这个是什么原因？是路由的版本关系？

**Comment by CJY0208** [comment]
可能是路由版本关系的原因，umi 使用的路由版本和插件中约定不一致？

**Comment by wangyinwei1** [comment]
那我们应该用什么版本才不会报错？可以告知下吗

**Comment by CJY0208** [comment]
你的 umi 版本号是多少？或者还是用的 alita

**Comment by wangyinwei1** [comment]
![image](https://user-images.githubusercontent.com/15857725/71155836-95edd380-2279-11ea-93c4-e459fd40c321.png)
umi-plugin-cache-route 2.0
