### ISSUE TITLE
alita 是否后续会支持打包生成小程序呢~

### ISSUE THREAD

**Issue by spwuc** [alitajs/alita#648]
目前在项目开发初期~ ailita 用过一次之后感觉爱不释手。但是目前新开的这个项目可能后期会用到小程序。如果alita会考虑生成小程序代码会大大减少开发成本！

**Comment by xiaohuoni** [comment]
哈哈哈，你说的对，但是会大大增加我的开发成本。
小程序是 taro 的主场，我们自己是通过小程序的 webview 接入了 web 页面的。
我暂时没有要生成小程序源码的计划

**Comment by spwuc** [comment]
get it .
