### ISSUE TITLE
多标签tabs关闭最后一个标签会出现页面崩溃问题

### ISSUE THREAD

**Issue by Emperorywh** [alitajs/alita#652]
关于，.umi ---plugin-keepalive ---context会报错，

代码在149行

![6e1eec457945f70dcd52250deaf1f34](https://github.com/alitajs/alita/assets/44226505/0e3889d7-4112-4b62-8ef8-4802e8215ac4)

**Comment by xiaohuoni** [comment]
这咋啦？就是不让关闭最后一个标签？

**Comment by Emperorywh** [comment]
> 这咋啦？就是不让关闭最后一个标签？
没有引入 message
![企业微信截图_1713922749329](https://github.com/alitajs/alita/assets/44226505/c50a58ce-9b18-4fe5-8b63-6aaf798337af)

**Comment by tangbzai** [comment]
如果是antd5的话，有可能是静态方法转 hooks 导致的
> [静态方法之痛 - Ant Desgin](https://ant.design/docs/blog/why-not-static-cn)
