### ISSUE TITLE
项目刚开始加载的加载动画可以自定义吗？或者改变加载icon的颜色

### ISSUE THREAD

**Issue by spwuc** [alitajs/alita#655]
目前没有找到修改的地方。
![image](https://github.com/alitajs/alita/assets/3370127/d468f997-1898-41f7-bca7-907cf6d82dff)

**Comment by xiaohuoni** [comment]
通过项目中的 plugin 插件可以修改，用这个 api https://umijs.org/docs/api/plugin-api#modifyhtml
