### ISSUE TITLE
多 tabs 和 FooterToolbar等底部组件兼容性问题

### ISSUE THREAD

**Issue by wojoc** [alitajs/alita#673]
[bug-demo.zip](https://github.com/user-attachments/files/17499491/bug-demo.zip)
您好，在页面切换的时候，不会将图示的资源切换，FooterToolbar等底部组件会一直出现在页面资源中，若存在相同资源则会覆盖，不存在相同资源则持续显示
![image](https://github.com/user-attachments/assets/9267cfb0-c85d-4dea-ba65-1d018e5b0fef)

**Comment by xiaohuoni** [comment]
因为这个组件只在销毁的时候控制
https://github.com/ant-design/pro-components/blob/master/packages/layout/src/components/FooterToolbar/index.tsx#L88

**Comment by wojoc** [comment]
明白了，那在页面切换的时候有方法控制吗，还是说要规避此类组件
