### ISSUE TITLE
umi-plugin-cache-route报错

### ISSUE THREAD

**Issue by yruson** [alitajs/alita#81]
在umi中tabs中用umi-plugin-cache-route时，切换tab页并伴随route更新，会不定时报如下错误，同一个tab项有时报错有时又不报：

`index.js:1 Warning: Failed prop type: The prop `match` is marked as required in `CacheSwitch`, but its value is `null`.
    in CacheSwitch (created by Context.Consumer)
    in withRouter(CacheSwitch) (created by Updatable)
    in Updatable (created by CacheComponent)
    in div (created by CacheComponent)
    in CacheComponent (created by Context.Consumer)
    in Route (created by CacheRoute)
    in CacheRoute (created by RouteWithProps)
    in RouteWithProps (created by Updatable)
    in SwitchFragment (created by Updatable)
    in Updatable (created by CacheSwitch)`

**Comment by xiaohuoni** [comment]
umi-plugin-cache-route 这个只是一个测试方案。验证了很多情况都不符合预期，所以这个废弃不用了，keepalive方案，估计要等umi@3看看了。
